// Code generated by ent, DO NOT EDIT.

package packageversion

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the packageversion type in the database.
	Label = "package_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPackageID holds the string denoting the package_id field in the database.
	FieldPackageID = "package_id"
	// FieldRevision holds the string denoting the revision field in the database.
	FieldRevision = "revision"
	// FieldSourceDigest holds the string denoting the source_digest field in the database.
	FieldSourceDigest = "source_digest"
	// FieldPkgver holds the string denoting the pkgver field in the database.
	FieldPkgver = "pkgver"
	// FieldPkgrel holds the string denoting the pkgrel field in the database.
	FieldPkgrel = "pkgrel"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldFirstSeenAt holds the string denoting the first_seen_at field in the database.
	FieldFirstSeenAt = "first_seen_at"
	// Table holds the table name of the packageversion in the database.
	Table = "package_versions"
)

// Columns holds all SQL columns for packageversion fields.
var Columns = []string{
	FieldID,
	FieldPackageID,
	FieldRevision,
	FieldSourceDigest,
	FieldPkgver,
	FieldPkgrel,
	FieldMetadata,
	FieldFirstSeenAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the PackageVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPackageID orders the results by the package_id field.
func ByPackageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPackageID, opts...).ToFunc()
}

// ByRevision orders the results by the revision field.
func ByRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevision, opts...).ToFunc()
}

// BySourceDigest orders the results by the source_digest field.
func BySourceDigest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceDigest, opts...).ToFunc()
}

// ByPkgver orders the results by the pkgver field.
func ByPkgver(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPkgver, opts...).ToFunc()
}

// ByPkgrel orders the results by the pkgrel field.
func ByPkgrel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPkgrel, opts...).ToFunc()
}

// ByFirstSeenAt orders the results by the first_seen_at field.
func ByFirstSeenAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstSeenAt, opts...).ToFunc()
}
