// Code generated by ent, DO NOT EDIT.

package packageversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/dudebehinddude/aurforge/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLTE(FieldID, id))
}

// PackageID applies equality check predicate on the "package_id" field. It's identical to PackageIDEQ.
func PackageID(v int64) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldPackageID, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldRevision, v))
}

// SourceDigest applies equality check predicate on the "source_digest" field. It's identical to SourceDigestEQ.
func SourceDigest(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldSourceDigest, v))
}

// Pkgver applies equality check predicate on the "pkgver" field. It's identical to PkgverEQ.
func Pkgver(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldPkgver, v))
}

// Pkgrel applies equality check predicate on the "pkgrel" field. It's identical to PkgrelEQ.
func Pkgrel(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldPkgrel, v))
}

// FirstSeenAt applies equality check predicate on the "first_seen_at" field. It's identical to FirstSeenAtEQ.
func FirstSeenAt(v time.Time) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldFirstSeenAt, v))
}

// PackageIDEQ applies the EQ predicate on the "package_id" field.
func PackageIDEQ(v int64) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldPackageID, v))
}

// PackageIDNEQ applies the NEQ predicate on the "package_id" field.
func PackageIDNEQ(v int64) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNEQ(FieldPackageID, v))
}

// PackageIDIn applies the In predicate on the "package_id" field.
func PackageIDIn(vs ...int64) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldIn(FieldPackageID, vs...))
}

// PackageIDNotIn applies the NotIn predicate on the "package_id" field.
func PackageIDNotIn(vs ...int64) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNotIn(FieldPackageID, vs...))
}

// PackageIDGT applies the GT predicate on the "package_id" field.
func PackageIDGT(v int64) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGT(FieldPackageID, v))
}

// PackageIDGTE applies the GTE predicate on the "package_id" field.
func PackageIDGTE(v int64) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGTE(FieldPackageID, v))
}

// PackageIDLT applies the LT predicate on the "package_id" field.
func PackageIDLT(v int64) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLT(FieldPackageID, v))
}

// PackageIDLTE applies the LTE predicate on the "package_id" field.
func PackageIDLTE(v int64) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLTE(FieldPackageID, v))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLTE(FieldRevision, v))
}

// RevisionContains applies the Contains predicate on the "revision" field.
func RevisionContains(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldContains(FieldRevision, v))
}

// RevisionHasPrefix applies the HasPrefix predicate on the "revision" field.
func RevisionHasPrefix(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldHasPrefix(FieldRevision, v))
}

// RevisionHasSuffix applies the HasSuffix predicate on the "revision" field.
func RevisionHasSuffix(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldHasSuffix(FieldRevision, v))
}

// RevisionEqualFold applies the EqualFold predicate on the "revision" field.
func RevisionEqualFold(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEqualFold(FieldRevision, v))
}

// RevisionContainsFold applies the ContainsFold predicate on the "revision" field.
func RevisionContainsFold(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldContainsFold(FieldRevision, v))
}

// SourceDigestEQ applies the EQ predicate on the "source_digest" field.
func SourceDigestEQ(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldSourceDigest, v))
}

// SourceDigestNEQ applies the NEQ predicate on the "source_digest" field.
func SourceDigestNEQ(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNEQ(FieldSourceDigest, v))
}

// SourceDigestIn applies the In predicate on the "source_digest" field.
func SourceDigestIn(vs ...string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldIn(FieldSourceDigest, vs...))
}

// SourceDigestNotIn applies the NotIn predicate on the "source_digest" field.
func SourceDigestNotIn(vs ...string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNotIn(FieldSourceDigest, vs...))
}

// SourceDigestGT applies the GT predicate on the "source_digest" field.
func SourceDigestGT(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGT(FieldSourceDigest, v))
}

// SourceDigestGTE applies the GTE predicate on the "source_digest" field.
func SourceDigestGTE(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGTE(FieldSourceDigest, v))
}

// SourceDigestLT applies the LT predicate on the "source_digest" field.
func SourceDigestLT(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLT(FieldSourceDigest, v))
}

// SourceDigestLTE applies the LTE predicate on the "source_digest" field.
func SourceDigestLTE(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLTE(FieldSourceDigest, v))
}

// SourceDigestContains applies the Contains predicate on the "source_digest" field.
func SourceDigestContains(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldContains(FieldSourceDigest, v))
}

// SourceDigestHasPrefix applies the HasPrefix predicate on the "source_digest" field.
func SourceDigestHasPrefix(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldHasPrefix(FieldSourceDigest, v))
}

// SourceDigestHasSuffix applies the HasSuffix predicate on the "source_digest" field.
func SourceDigestHasSuffix(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldHasSuffix(FieldSourceDigest, v))
}

// SourceDigestEqualFold applies the EqualFold predicate on the "source_digest" field.
func SourceDigestEqualFold(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEqualFold(FieldSourceDigest, v))
}

// SourceDigestContainsFold applies the ContainsFold predicate on the "source_digest" field.
func SourceDigestContainsFold(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldContainsFold(FieldSourceDigest, v))
}

// PkgverEQ applies the EQ predicate on the "pkgver" field.
func PkgverEQ(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldPkgver, v))
}

// PkgverNEQ applies the NEQ predicate on the "pkgver" field.
func PkgverNEQ(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNEQ(FieldPkgver, v))
}

// PkgverIn applies the In predicate on the "pkgver" field.
func PkgverIn(vs ...string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldIn(FieldPkgver, vs...))
}

// PkgverNotIn applies the NotIn predicate on the "pkgver" field.
func PkgverNotIn(vs ...string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNotIn(FieldPkgver, vs...))
}

// PkgverGT applies the GT predicate on the "pkgver" field.
func PkgverGT(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGT(FieldPkgver, v))
}

// PkgverGTE applies the GTE predicate on the "pkgver" field.
func PkgverGTE(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGTE(FieldPkgver, v))
}

// PkgverLT applies the LT predicate on the "pkgver" field.
func PkgverLT(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLT(FieldPkgver, v))
}

// PkgverLTE applies the LTE predicate on the "pkgver" field.
func PkgverLTE(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLTE(FieldPkgver, v))
}

// PkgverContains applies the Contains predicate on the "pkgver" field.
func PkgverContains(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldContains(FieldPkgver, v))
}

// PkgverHasPrefix applies the HasPrefix predicate on the "pkgver" field.
func PkgverHasPrefix(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldHasPrefix(FieldPkgver, v))
}

// PkgverHasSuffix applies the HasSuffix predicate on the "pkgver" field.
func PkgverHasSuffix(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldHasSuffix(FieldPkgver, v))
}

// PkgverEqualFold applies the EqualFold predicate on the "pkgver" field.
func PkgverEqualFold(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEqualFold(FieldPkgver, v))
}

// PkgverContainsFold applies the ContainsFold predicate on the "pkgver" field.
func PkgverContainsFold(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldContainsFold(FieldPkgver, v))
}

// PkgrelEQ applies the EQ predicate on the "pkgrel" field.
func PkgrelEQ(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldPkgrel, v))
}

// PkgrelNEQ applies the NEQ predicate on the "pkgrel" field.
func PkgrelNEQ(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNEQ(FieldPkgrel, v))
}

// PkgrelIn applies the In predicate on the "pkgrel" field.
func PkgrelIn(vs ...string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldIn(FieldPkgrel, vs...))
}

// PkgrelNotIn applies the NotIn predicate on the "pkgrel" field.
func PkgrelNotIn(vs ...string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNotIn(FieldPkgrel, vs...))
}

// PkgrelGT applies the GT predicate on the "pkgrel" field.
func PkgrelGT(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGT(FieldPkgrel, v))
}

// PkgrelGTE applies the GTE predicate on the "pkgrel" field.
func PkgrelGTE(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGTE(FieldPkgrel, v))
}

// PkgrelLT applies the LT predicate on the "pkgrel" field.
func PkgrelLT(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLT(FieldPkgrel, v))
}

// PkgrelLTE applies the LTE predicate on the "pkgrel" field.
func PkgrelLTE(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLTE(FieldPkgrel, v))
}

// PkgrelContains applies the Contains predicate on the "pkgrel" field.
func PkgrelContains(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldContains(FieldPkgrel, v))
}

// PkgrelHasPrefix applies the HasPrefix predicate on the "pkgrel" field.
func PkgrelHasPrefix(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldHasPrefix(FieldPkgrel, v))
}

// PkgrelHasSuffix applies the HasSuffix predicate on the "pkgrel" field.
func PkgrelHasSuffix(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldHasSuffix(FieldPkgrel, v))
}

// PkgrelEqualFold applies the EqualFold predicate on the "pkgrel" field.
func PkgrelEqualFold(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEqualFold(FieldPkgrel, v))
}

// PkgrelContainsFold applies the ContainsFold predicate on the "pkgrel" field.
func PkgrelContainsFold(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldContainsFold(FieldPkgrel, v))
}

// FirstSeenAtEQ applies the EQ predicate on the "first_seen_at" field.
func FirstSeenAtEQ(v time.Time) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldFirstSeenAt, v))
}

// FirstSeenAtNEQ applies the NEQ predicate on the "first_seen_at" field.
func FirstSeenAtNEQ(v time.Time) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNEQ(FieldFirstSeenAt, v))
}

// FirstSeenAtIn applies the In predicate on the "first_seen_at" field.
func FirstSeenAtIn(vs ...time.Time) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldIn(FieldFirstSeenAt, vs...))
}

// FirstSeenAtNotIn applies the NotIn predicate on the "first_seen_at" field.
func FirstSeenAtNotIn(vs ...time.Time) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNotIn(FieldFirstSeenAt, vs...))
}

// FirstSeenAtGT applies the GT predicate on the "first_seen_at" field.
func FirstSeenAtGT(v time.Time) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGT(FieldFirstSeenAt, v))
}

// FirstSeenAtGTE applies the GTE predicate on the "first_seen_at" field.
func FirstSeenAtGTE(v time.Time) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGTE(FieldFirstSeenAt, v))
}

// FirstSeenAtLT applies the LT predicate on the "first_seen_at" field.
func FirstSeenAtLT(v time.Time) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLT(FieldFirstSeenAt, v))
}

// FirstSeenAtLTE applies the LTE predicate on the "first_seen_at" field.
func FirstSeenAtLTE(v time.Time) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLTE(FieldFirstSeenAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PackageVersion) predicate.PackageVersion {
	return predicate.PackageVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PackageVersion) predicate.PackageVersion {
	return predicate.PackageVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PackageVersion) predicate.PackageVersion {
	return predicate.PackageVersion(sql.NotPredicates(p))
}
