// Code generated by ent, DO NOT EDIT.

package job

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/dudebehinddude/aurforge/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldID, id))
}

// PackageVersionID applies equality check predicate on the "package_version_id" field. It's identical to PackageVersionIDEQ.
func PackageVersionID(v int64) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldPackageVersionID, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldKind, v))
}

// EligibleAt applies equality check predicate on the "eligible_at" field. It's identical to EligibleAtEQ.
func EligibleAt(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldEligibleAt, v))
}

// ClaimedAt applies equality check predicate on the "claimed_at" field. It's identical to ClaimedAtEQ.
func ClaimedAt(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldClaimedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldFinishedAt, v))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldAttempts, v))
}

// LogPath applies equality check predicate on the "log_path" field. It's identical to LogPathEQ.
func LogPath(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldLogPath, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldError, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCreatedAt, v))
}

// PackageVersionIDEQ applies the EQ predicate on the "package_version_id" field.
func PackageVersionIDEQ(v int64) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldPackageVersionID, v))
}

// PackageVersionIDNEQ applies the NEQ predicate on the "package_version_id" field.
func PackageVersionIDNEQ(v int64) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldPackageVersionID, v))
}

// PackageVersionIDIn applies the In predicate on the "package_version_id" field.
func PackageVersionIDIn(vs ...int64) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldPackageVersionID, vs...))
}

// PackageVersionIDNotIn applies the NotIn predicate on the "package_version_id" field.
func PackageVersionIDNotIn(vs ...int64) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldPackageVersionID, vs...))
}

// PackageVersionIDGT applies the GT predicate on the "package_version_id" field.
func PackageVersionIDGT(v int64) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldPackageVersionID, v))
}

// PackageVersionIDGTE applies the GTE predicate on the "package_version_id" field.
func PackageVersionIDGTE(v int64) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldPackageVersionID, v))
}

// PackageVersionIDLT applies the LT predicate on the "package_version_id" field.
func PackageVersionIDLT(v int64) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldPackageVersionID, v))
}

// PackageVersionIDLTE applies the LTE predicate on the "package_version_id" field.
func PackageVersionIDLTE(v int64) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldPackageVersionID, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldKind, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldStatus, vs...))
}

// EligibleAtEQ applies the EQ predicate on the "eligible_at" field.
func EligibleAtEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldEligibleAt, v))
}

// EligibleAtNEQ applies the NEQ predicate on the "eligible_at" field.
func EligibleAtNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldEligibleAt, v))
}

// EligibleAtIn applies the In predicate on the "eligible_at" field.
func EligibleAtIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldEligibleAt, vs...))
}

// EligibleAtNotIn applies the NotIn predicate on the "eligible_at" field.
func EligibleAtNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldEligibleAt, vs...))
}

// EligibleAtGT applies the GT predicate on the "eligible_at" field.
func EligibleAtGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldEligibleAt, v))
}

// EligibleAtGTE applies the GTE predicate on the "eligible_at" field.
func EligibleAtGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldEligibleAt, v))
}

// EligibleAtLT applies the LT predicate on the "eligible_at" field.
func EligibleAtLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldEligibleAt, v))
}

// EligibleAtLTE applies the LTE predicate on the "eligible_at" field.
func EligibleAtLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldEligibleAt, v))
}

// ClaimedAtEQ applies the EQ predicate on the "claimed_at" field.
func ClaimedAtEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldClaimedAt, v))
}

// ClaimedAtNEQ applies the NEQ predicate on the "claimed_at" field.
func ClaimedAtNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldClaimedAt, v))
}

// ClaimedAtIn applies the In predicate on the "claimed_at" field.
func ClaimedAtIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldClaimedAt, vs...))
}

// ClaimedAtNotIn applies the NotIn predicate on the "claimed_at" field.
func ClaimedAtNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldClaimedAt, vs...))
}

// ClaimedAtGT applies the GT predicate on the "claimed_at" field.
func ClaimedAtGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldClaimedAt, v))
}

// ClaimedAtGTE applies the GTE predicate on the "claimed_at" field.
func ClaimedAtGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldClaimedAt, v))
}

// ClaimedAtLT applies the LT predicate on the "claimed_at" field.
func ClaimedAtLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldClaimedAt, v))
}

// ClaimedAtLTE applies the LTE predicate on the "claimed_at" field.
func ClaimedAtLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldClaimedAt, v))
}

// ClaimedAtIsNil applies the IsNil predicate on the "claimed_at" field.
func ClaimedAtIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldClaimedAt))
}

// ClaimedAtNotNil applies the NotNil predicate on the "claimed_at" field.
func ClaimedAtNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldClaimedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldFinishedAt))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldAttempts, v))
}

// LogPathEQ applies the EQ predicate on the "log_path" field.
func LogPathEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldLogPath, v))
}

// LogPathNEQ applies the NEQ predicate on the "log_path" field.
func LogPathNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldLogPath, v))
}

// LogPathIn applies the In predicate on the "log_path" field.
func LogPathIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldLogPath, vs...))
}

// LogPathNotIn applies the NotIn predicate on the "log_path" field.
func LogPathNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldLogPath, vs...))
}

// LogPathGT applies the GT predicate on the "log_path" field.
func LogPathGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldLogPath, v))
}

// LogPathGTE applies the GTE predicate on the "log_path" field.
func LogPathGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldLogPath, v))
}

// LogPathLT applies the LT predicate on the "log_path" field.
func LogPathLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldLogPath, v))
}

// LogPathLTE applies the LTE predicate on the "log_path" field.
func LogPathLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldLogPath, v))
}

// LogPathContains applies the Contains predicate on the "log_path" field.
func LogPathContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldLogPath, v))
}

// LogPathHasPrefix applies the HasPrefix predicate on the "log_path" field.
func LogPathHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldLogPath, v))
}

// LogPathHasSuffix applies the HasSuffix predicate on the "log_path" field.
func LogPathHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldLogPath, v))
}

// LogPathIsNil applies the IsNil predicate on the "log_path" field.
func LogPathIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldLogPath))
}

// LogPathNotNil applies the NotNil predicate on the "log_path" field.
func LogPathNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldLogPath))
}

// LogPathEqualFold applies the EqualFold predicate on the "log_path" field.
func LogPathEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldLogPath, v))
}

// LogPathContainsFold applies the ContainsFold predicate on the "log_path" field.
func LogPathContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldLogPath, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Job) predicate.Job {
	return predicate.Job(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Job) predicate.Job {
	return predicate.Job(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Job) predicate.Job {
	return predicate.Job(sql.NotPredicates(p))
}
