// Code generated by ent, DO NOT EDIT.

package managedpackage

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the managedpackage type in the database.
	Label = "managed_package"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSourceKind holds the string denoting the source_kind field in the database.
	FieldSourceKind = "source_kind"
	// FieldSourceRef holds the string denoting the source_ref field in the database.
	FieldSourceRef = "source_ref"
	// FieldSourcePath holds the string denoting the source_path field in the database.
	FieldSourcePath = "source_path"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the managedpackage in the database.
	Table = "managed_packages"
)

// Columns holds all SQL columns for managedpackage fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSourceKind,
	FieldSourceRef,
	FieldSourcePath,
	FieldEnabled,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// SourceKind defines the type for the "source_kind" enum field.
type SourceKind string

// SourceKind values.
const (
	SourceKindAur   SourceKind = "aur"
	SourceKindLocal SourceKind = "local"
)

func (sk SourceKind) String() string {
	return string(sk)
}

// SourceKindValidator is a validator for the "source_kind" field enum values. It is called by the builders before save.
func SourceKindValidator(sk SourceKind) error {
	switch sk {
	case SourceKindAur, SourceKindLocal:
		return nil
	default:
		return fmt.Errorf("managedpackage: invalid enum value for source_kind field: %q", sk)
	}
}

// OrderOption defines the ordering options for the ManagedPackage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySourceKind orders the results by the source_kind field.
func BySourceKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceKind, opts...).ToFunc()
}

// BySourceRef orders the results by the source_ref field.
func BySourceRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceRef, opts...).ToFunc()
}

// BySourcePath orders the results by the source_path field.
func BySourcePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourcePath, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
