// Code generated by ent, DO NOT EDIT.

package managedpackage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/dudebehinddude/aurforge/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldName, v))
}

// SourceRef applies equality check predicate on the "source_ref" field. It's identical to SourceRefEQ.
func SourceRef(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldSourceRef, v))
}

// SourcePath applies equality check predicate on the "source_path" field. It's identical to SourcePathEQ.
func SourcePath(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldSourcePath, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldName, v))
}

// SourceKindEQ applies the EQ predicate on the "source_kind" field.
func SourceKindEQ(v SourceKind) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldSourceKind, v))
}

// SourceKindNEQ applies the NEQ predicate on the "source_kind" field.
func SourceKindNEQ(v SourceKind) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldSourceKind, v))
}

// SourceKindIn applies the In predicate on the "source_kind" field.
func SourceKindIn(vs ...SourceKind) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldSourceKind, vs...))
}

// SourceKindNotIn applies the NotIn predicate on the "source_kind" field.
func SourceKindNotIn(vs ...SourceKind) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldSourceKind, vs...))
}

// SourceRefEQ applies the EQ predicate on the "source_ref" field.
func SourceRefEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldSourceRef, v))
}

// SourceRefNEQ applies the NEQ predicate on the "source_ref" field.
func SourceRefNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldSourceRef, v))
}

// SourceRefIn applies the In predicate on the "source_ref" field.
func SourceRefIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldSourceRef, vs...))
}

// SourceRefNotIn applies the NotIn predicate on the "source_ref" field.
func SourceRefNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldSourceRef, vs...))
}

// SourceRefGT applies the GT predicate on the "source_ref" field.
func SourceRefGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldSourceRef, v))
}

// SourceRefGTE applies the GTE predicate on the "source_ref" field.
func SourceRefGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldSourceRef, v))
}

// SourceRefLT applies the LT predicate on the "source_ref" field.
func SourceRefLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldSourceRef, v))
}

// SourceRefLTE applies the LTE predicate on the "source_ref" field.
func SourceRefLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldSourceRef, v))
}

// SourceRefContains applies the Contains predicate on the "source_ref" field.
func SourceRefContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldSourceRef, v))
}

// SourceRefHasPrefix applies the HasPrefix predicate on the "source_ref" field.
func SourceRefHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldSourceRef, v))
}

// SourceRefHasSuffix applies the HasSuffix predicate on the "source_ref" field.
func SourceRefHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldSourceRef, v))
}

// SourceRefEqualFold applies the EqualFold predicate on the "source_ref" field.
func SourceRefEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldSourceRef, v))
}

// SourceRefContainsFold applies the ContainsFold predicate on the "source_ref" field.
func SourceRefContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldSourceRef, v))
}

// SourcePathEQ applies the EQ predicate on the "source_path" field.
func SourcePathEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldSourcePath, v))
}

// SourcePathNEQ applies the NEQ predicate on the "source_path" field.
func SourcePathNEQ(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldSourcePath, v))
}

// SourcePathIn applies the In predicate on the "source_path" field.
func SourcePathIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldSourcePath, vs...))
}

// SourcePathNotIn applies the NotIn predicate on the "source_path" field.
func SourcePathNotIn(vs ...string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldSourcePath, vs...))
}

// SourcePathGT applies the GT predicate on the "source_path" field.
func SourcePathGT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldSourcePath, v))
}

// SourcePathGTE applies the GTE predicate on the "source_path" field.
func SourcePathGTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldSourcePath, v))
}

// SourcePathLT applies the LT predicate on the "source_path" field.
func SourcePathLT(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldSourcePath, v))
}

// SourcePathLTE applies the LTE predicate on the "source_path" field.
func SourcePathLTE(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldSourcePath, v))
}

// SourcePathContains applies the Contains predicate on the "source_path" field.
func SourcePathContains(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContains(FieldSourcePath, v))
}

// SourcePathHasPrefix applies the HasPrefix predicate on the "source_path" field.
func SourcePathHasPrefix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasPrefix(FieldSourcePath, v))
}

// SourcePathHasSuffix applies the HasSuffix predicate on the "source_path" field.
func SourcePathHasSuffix(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldHasSuffix(FieldSourcePath, v))
}

// SourcePathEqualFold applies the EqualFold predicate on the "source_path" field.
func SourcePathEqualFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEqualFold(FieldSourcePath, v))
}

// SourcePathContainsFold applies the ContainsFold predicate on the "source_path" field.
func SourcePathContainsFold(v string) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldContainsFold(FieldSourcePath, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ManagedPackage) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ManagedPackage) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ManagedPackage) predicate.ManagedPackage {
	return predicate.ManagedPackage(sql.NotPredicates(p))
}
