// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ArtifactsColumns holds the columns for the "artifacts" table.
	ArtifactsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "job_id", Type: field.TypeInt64},
		{Name: "filename", Type: field.TypeString},
		{Name: "sha256", Type: field.TypeString},
		{Name: "size_bytes", Type: field.TypeInt64},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
	}
	// ArtifactsTable holds the schema information for the "artifacts" table.
	ArtifactsTable = &schema.Table{
		Name:       "artifacts",
		Columns:    ArtifactsColumns,
		PrimaryKey: []*schema.Column{ArtifactsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "artifact_job_id_filename",
				Unique:  true,
				Columns: []*schema.Column{ArtifactsColumns[1], ArtifactsColumns[2]},
			},
		},
	}
	// AuditEventsColumns holds the columns for the "audit_events" table.
	AuditEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "package_version_id", Type: field.TypeInt64},
		{Name: "severity", Type: field.TypeString},
		{Name: "code", Type: field.TypeString},
		{Name: "detail", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AuditEventsTable holds the schema information for the "audit_events" table.
	AuditEventsTable = &schema.Table{
		Name:       "audit_events",
		Columns:    AuditEventsColumns,
		PrimaryKey: []*schema.Column{AuditEventsColumns[0]},
	}
	// DependenciesColumns holds the columns for the "dependencies" table.
	DependenciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "package_version_id", Type: field.TypeInt64},
		{Name: "dependency_name", Type: field.TypeString},
		{Name: "dependency_kind", Type: field.TypeEnum, Enums: []string{"repo", "aur"}},
	}
	// DependenciesTable holds the schema information for the "dependencies" table.
	DependenciesTable = &schema.Table{
		Name:       "dependencies",
		Columns:    DependenciesColumns,
		PrimaryKey: []*schema.Column{DependenciesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "dependency_package_version_id_dependency_name",
				Unique:  true,
				Columns: []*schema.Column{DependenciesColumns[1], DependenciesColumns[2]},
			},
		},
	}
	// JobsColumns holds the columns for the "jobs" table.
	JobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "package_version_id", Type: field.TypeInt64},
		{Name: "kind", Type: field.TypeString, Default: "build"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "running", "built", "published", "failed"}, Default: "pending"},
		{Name: "eligible_at", Type: field.TypeTime},
		{Name: "claimed_at", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "log_path", Type: field.TypeString, Nullable: true},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// JobsTable holds the schema information for the "jobs" table.
	JobsTable = &schema.Table{
		Name:       "jobs",
		Columns:    JobsColumns,
		PrimaryKey: []*schema.Column{JobsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "job_status_eligible_at",
				Unique:  false,
				Columns: []*schema.Column{JobsColumns[3], JobsColumns[4]},
			},
		},
	}
	// ManagedPackagesColumns holds the columns for the "managed_packages" table.
	ManagedPackagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "source_kind", Type: field.TypeEnum, Enums: []string{"aur", "local"}},
		{Name: "source_ref", Type: field.TypeString},
		{Name: "source_path", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ManagedPackagesTable holds the schema information for the "managed_packages" table.
	ManagedPackagesTable = &schema.Table{
		Name:       "managed_packages",
		Columns:    ManagedPackagesColumns,
		PrimaryKey: []*schema.Column{ManagedPackagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "managedpackage_name",
				Unique:  false,
				Columns: []*schema.Column{ManagedPackagesColumns[1]},
			},
		},
	}
	// PackageVersionsColumns holds the columns for the "package_versions" table.
	PackageVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "package_id", Type: field.TypeInt64},
		{Name: "revision", Type: field.TypeString},
		{Name: "source_digest", Type: field.TypeString},
		{Name: "pkgver", Type: field.TypeString},
		{Name: "pkgrel", Type: field.TypeString},
		{Name: "metadata", Type: field.TypeJSON},
		{Name: "first_seen_at", Type: field.TypeTime},
	}
	// PackageVersionsTable holds the schema information for the "package_versions" table.
	PackageVersionsTable = &schema.Table{
		Name:       "package_versions",
		Columns:    PackageVersionsColumns,
		PrimaryKey: []*schema.Column{PackageVersionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "packageversion_package_id_revision",
				Unique:  true,
				Columns: []*schema.Column{PackageVersionsColumns[1], PackageVersionsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ArtifactsTable,
		AuditEventsTable,
		DependenciesTable,
		JobsTable,
		ManagedPackagesTable,
		PackageVersionsTable,
	}
)

func init() {
}
