// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dudebehinddude/aurforge/ent/artifact"
	"github.com/dudebehinddude/aurforge/ent/predicate"
)

// ArtifactUpdate is the builder for updating Artifact entities.
type ArtifactUpdate struct {
	config
	hooks    []Hook
	mutation *ArtifactMutation
}

// Where appends a list predicates to the ArtifactUpdate builder.
func (_u *ArtifactUpdate) Where(ps ...predicate.Artifact) *ArtifactUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetJobID sets the "job_id" field.
func (_u *ArtifactUpdate) SetJobID(v int64) *ArtifactUpdate {
	_u.mutation.ResetJobID()
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *ArtifactUpdate) SetNillableJobID(v *int64) *ArtifactUpdate {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// AddJobID adds value to the "job_id" field.
func (_u *ArtifactUpdate) AddJobID(v int64) *ArtifactUpdate {
	_u.mutation.AddJobID(v)
	return _u
}

// SetFilename sets the "filename" field.
func (_u *ArtifactUpdate) SetFilename(v string) *ArtifactUpdate {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *ArtifactUpdate) SetNillableFilename(v *string) *ArtifactUpdate {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *ArtifactUpdate) SetSha256(v string) *ArtifactUpdate {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *ArtifactUpdate) SetNillableSha256(v *string) *ArtifactUpdate {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *ArtifactUpdate) SetSizeBytes(v int64) *ArtifactUpdate {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *ArtifactUpdate) SetNillableSizeBytes(v *int64) *ArtifactUpdate {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *ArtifactUpdate) AddSizeBytes(v int64) *ArtifactUpdate {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *ArtifactUpdate) SetPublishedAt(v time.Time) *ArtifactUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *ArtifactUpdate) SetNillablePublishedAt(v *time.Time) *ArtifactUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *ArtifactUpdate) ClearPublishedAt() *ArtifactUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// Mutation returns the ArtifactMutation object of the builder.
func (_u *ArtifactUpdate) Mutation() *ArtifactMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ArtifactUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArtifactUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ArtifactUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArtifactUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ArtifactUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(artifact.Table, artifact.Columns, sqlgraph.NewFieldSpec(artifact.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JobID(); ok {
		_spec.SetField(artifact.FieldJobID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedJobID(); ok {
		_spec.AddField(artifact.FieldJobID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(artifact.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(artifact.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(artifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(artifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(artifact.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(artifact.FieldPublishedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{artifact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ArtifactUpdateOne is the builder for updating a single Artifact entity.
type ArtifactUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArtifactMutation
}

// SetJobID sets the "job_id" field.
func (_u *ArtifactUpdateOne) SetJobID(v int64) *ArtifactUpdateOne {
	_u.mutation.ResetJobID()
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *ArtifactUpdateOne) SetNillableJobID(v *int64) *ArtifactUpdateOne {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// AddJobID adds value to the "job_id" field.
func (_u *ArtifactUpdateOne) AddJobID(v int64) *ArtifactUpdateOne {
	_u.mutation.AddJobID(v)
	return _u
}

// SetFilename sets the "filename" field.
func (_u *ArtifactUpdateOne) SetFilename(v string) *ArtifactUpdateOne {
	_u.mutation.SetFilename(v)
	return _u
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (_u *ArtifactUpdateOne) SetNillableFilename(v *string) *ArtifactUpdateOne {
	if v != nil {
		_u.SetFilename(*v)
	}
	return _u
}

// SetSha256 sets the "sha256" field.
func (_u *ArtifactUpdateOne) SetSha256(v string) *ArtifactUpdateOne {
	_u.mutation.SetSha256(v)
	return _u
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (_u *ArtifactUpdateOne) SetNillableSha256(v *string) *ArtifactUpdateOne {
	if v != nil {
		_u.SetSha256(*v)
	}
	return _u
}

// SetSizeBytes sets the "size_bytes" field.
func (_u *ArtifactUpdateOne) SetSizeBytes(v int64) *ArtifactUpdateOne {
	_u.mutation.ResetSizeBytes()
	_u.mutation.SetSizeBytes(v)
	return _u
}

// SetNillableSizeBytes sets the "size_bytes" field if the given value is not nil.
func (_u *ArtifactUpdateOne) SetNillableSizeBytes(v *int64) *ArtifactUpdateOne {
	if v != nil {
		_u.SetSizeBytes(*v)
	}
	return _u
}

// AddSizeBytes adds value to the "size_bytes" field.
func (_u *ArtifactUpdateOne) AddSizeBytes(v int64) *ArtifactUpdateOne {
	_u.mutation.AddSizeBytes(v)
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *ArtifactUpdateOne) SetPublishedAt(v time.Time) *ArtifactUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *ArtifactUpdateOne) SetNillablePublishedAt(v *time.Time) *ArtifactUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *ArtifactUpdateOne) ClearPublishedAt() *ArtifactUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// Mutation returns the ArtifactMutation object of the builder.
func (_u *ArtifactUpdateOne) Mutation() *ArtifactMutation {
	return _u.mutation
}

// Where appends a list predicates to the ArtifactUpdate builder.
func (_u *ArtifactUpdateOne) Where(ps ...predicate.Artifact) *ArtifactUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ArtifactUpdateOne) Select(field string, fields ...string) *ArtifactUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Artifact entity.
func (_u *ArtifactUpdateOne) Save(ctx context.Context) (*Artifact, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArtifactUpdateOne) SaveX(ctx context.Context) *Artifact {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ArtifactUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArtifactUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ArtifactUpdateOne) sqlSave(ctx context.Context) (_node *Artifact, err error) {
	_spec := sqlgraph.NewUpdateSpec(artifact.Table, artifact.Columns, sqlgraph.NewFieldSpec(artifact.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Artifact.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, artifact.FieldID)
		for _, f := range fields {
			if !artifact.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != artifact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JobID(); ok {
		_spec.SetField(artifact.FieldJobID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedJobID(); ok {
		_spec.AddField(artifact.FieldJobID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Filename(); ok {
		_spec.SetField(artifact.FieldFilename, field.TypeString, value)
	}
	if value, ok := _u.mutation.Sha256(); ok {
		_spec.SetField(artifact.FieldSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.SizeBytes(); ok {
		_spec.SetField(artifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSizeBytes(); ok {
		_spec.AddField(artifact.FieldSizeBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(artifact.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(artifact.FieldPublishedAt, field.TypeTime)
	}
	_node = &Artifact{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{artifact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
