// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dudebehinddude/aurforge/ent/artifact"
)

// ArtifactCreate is the builder for creating a Artifact entity.
type ArtifactCreate struct {
	config
	mutation *ArtifactMutation
	hooks    []Hook
}

// SetJobID sets the "job_id" field.
func (_c *ArtifactCreate) SetJobID(v int64) *ArtifactCreate {
	_c.mutation.SetJobID(v)
	return _c
}

// SetFilename sets the "filename" field.
func (_c *ArtifactCreate) SetFilename(v string) *ArtifactCreate {
	_c.mutation.SetFilename(v)
	return _c
}

// SetSha256 sets the "sha256" field.
func (_c *ArtifactCreate) SetSha256(v string) *ArtifactCreate {
	_c.mutation.SetSha256(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *ArtifactCreate) SetSizeBytes(v int64) *ArtifactCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *ArtifactCreate) SetPublishedAt(v time.Time) *ArtifactCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *ArtifactCreate) SetNillablePublishedAt(v *time.Time) *ArtifactCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// Mutation returns the ArtifactMutation object of the builder.
func (_c *ArtifactCreate) Mutation() *ArtifactMutation {
	return _c.mutation
}

// Save creates the Artifact in the database.
func (_c *ArtifactCreate) Save(ctx context.Context) (*Artifact, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ArtifactCreate) SaveX(ctx context.Context) *Artifact {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArtifactCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArtifactCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ArtifactCreate) check() error {
	if _, ok := _c.mutation.JobID(); !ok {
		return &ValidationError{Name: "job_id", err: errors.New(`ent: missing required field "Artifact.job_id"`)}
	}
	if _, ok := _c.mutation.Filename(); !ok {
		return &ValidationError{Name: "filename", err: errors.New(`ent: missing required field "Artifact.filename"`)}
	}
	if _, ok := _c.mutation.Sha256(); !ok {
		return &ValidationError{Name: "sha256", err: errors.New(`ent: missing required field "Artifact.sha256"`)}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "Artifact.size_bytes"`)}
	}
	return nil
}

func (_c *ArtifactCreate) sqlSave(ctx context.Context) (*Artifact, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ArtifactCreate) createSpec() (*Artifact, *sqlgraph.CreateSpec) {
	var (
		_node = &Artifact{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(artifact.Table, sqlgraph.NewFieldSpec(artifact.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.JobID(); ok {
		_spec.SetField(artifact.FieldJobID, field.TypeInt64, value)
		_node.JobID = value
	}
	if value, ok := _c.mutation.Filename(); ok {
		_spec.SetField(artifact.FieldFilename, field.TypeString, value)
		_node.Filename = value
	}
	if value, ok := _c.mutation.Sha256(); ok {
		_spec.SetField(artifact.FieldSha256, field.TypeString, value)
		_node.Sha256 = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(artifact.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(artifact.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	return _node, _spec
}

// ArtifactCreateBulk is the builder for creating many Artifact entities in bulk.
type ArtifactCreateBulk struct {
	config
	err      error
	builders []*ArtifactCreate
}

// Save creates the Artifact entities in the database.
func (_c *ArtifactCreateBulk) Save(ctx context.Context) ([]*Artifact, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Artifact, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArtifactMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ArtifactCreateBulk) SaveX(ctx context.Context) []*Artifact {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArtifactCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArtifactCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
