// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dudebehinddude/aurforge/ent/auditevent"
	"github.com/dudebehinddude/aurforge/ent/predicate"
)

// AuditEventUpdate is the builder for updating AuditEvent entities.
type AuditEventUpdate struct {
	config
	hooks    []Hook
	mutation *AuditEventMutation
}

// Where appends a list predicates to the AuditEventUpdate builder.
func (_u *AuditEventUpdate) Where(ps ...predicate.AuditEvent) *AuditEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPackageVersionID sets the "package_version_id" field.
func (_u *AuditEventUpdate) SetPackageVersionID(v int64) *AuditEventUpdate {
	_u.mutation.ResetPackageVersionID()
	_u.mutation.SetPackageVersionID(v)
	return _u
}

// SetNillablePackageVersionID sets the "package_version_id" field if the given value is not nil.
func (_u *AuditEventUpdate) SetNillablePackageVersionID(v *int64) *AuditEventUpdate {
	if v != nil {
		_u.SetPackageVersionID(*v)
	}
	return _u
}

// AddPackageVersionID adds value to the "package_version_id" field.
func (_u *AuditEventUpdate) AddPackageVersionID(v int64) *AuditEventUpdate {
	_u.mutation.AddPackageVersionID(v)
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *AuditEventUpdate) SetSeverity(v string) *AuditEventUpdate {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *AuditEventUpdate) SetNillableSeverity(v *string) *AuditEventUpdate {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *AuditEventUpdate) SetCode(v string) *AuditEventUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *AuditEventUpdate) SetNillableCode(v *string) *AuditEventUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDetail sets the "detail" field.
func (_u *AuditEventUpdate) SetDetail(v string) *AuditEventUpdate {
	_u.mutation.SetDetail(v)
	return _u
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_u *AuditEventUpdate) SetNillableDetail(v *string) *AuditEventUpdate {
	if v != nil {
		_u.SetDetail(*v)
	}
	return _u
}

// Mutation returns the AuditEventMutation object of the builder.
func (_u *AuditEventUpdate) Mutation() *AuditEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuditEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(auditevent.Table, auditevent.Columns, sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PackageVersionID(); ok {
		_spec.SetField(auditevent.FieldPackageVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPackageVersionID(); ok {
		_spec.AddField(auditevent.FieldPackageVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(auditevent.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(auditevent.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(auditevent.FieldDetail, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditEventUpdateOne is the builder for updating a single AuditEvent entity.
type AuditEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditEventMutation
}

// SetPackageVersionID sets the "package_version_id" field.
func (_u *AuditEventUpdateOne) SetPackageVersionID(v int64) *AuditEventUpdateOne {
	_u.mutation.ResetPackageVersionID()
	_u.mutation.SetPackageVersionID(v)
	return _u
}

// SetNillablePackageVersionID sets the "package_version_id" field if the given value is not nil.
func (_u *AuditEventUpdateOne) SetNillablePackageVersionID(v *int64) *AuditEventUpdateOne {
	if v != nil {
		_u.SetPackageVersionID(*v)
	}
	return _u
}

// AddPackageVersionID adds value to the "package_version_id" field.
func (_u *AuditEventUpdateOne) AddPackageVersionID(v int64) *AuditEventUpdateOne {
	_u.mutation.AddPackageVersionID(v)
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *AuditEventUpdateOne) SetSeverity(v string) *AuditEventUpdateOne {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *AuditEventUpdateOne) SetNillableSeverity(v *string) *AuditEventUpdateOne {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *AuditEventUpdateOne) SetCode(v string) *AuditEventUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *AuditEventUpdateOne) SetNillableCode(v *string) *AuditEventUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDetail sets the "detail" field.
func (_u *AuditEventUpdateOne) SetDetail(v string) *AuditEventUpdateOne {
	_u.mutation.SetDetail(v)
	return _u
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_u *AuditEventUpdateOne) SetNillableDetail(v *string) *AuditEventUpdateOne {
	if v != nil {
		_u.SetDetail(*v)
	}
	return _u
}

// Mutation returns the AuditEventMutation object of the builder.
func (_u *AuditEventUpdateOne) Mutation() *AuditEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuditEventUpdate builder.
func (_u *AuditEventUpdateOne) Where(ps ...predicate.AuditEvent) *AuditEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditEventUpdateOne) Select(field string, fields ...string) *AuditEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditEvent entity.
func (_u *AuditEventUpdateOne) Save(ctx context.Context) (*AuditEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditEventUpdateOne) SaveX(ctx context.Context) *AuditEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuditEventUpdateOne) sqlSave(ctx context.Context) (_node *AuditEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(auditevent.Table, auditevent.Columns, sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditevent.FieldID)
		for _, f := range fields {
			if !auditevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PackageVersionID(); ok {
		_spec.SetField(auditevent.FieldPackageVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPackageVersionID(); ok {
		_spec.AddField(auditevent.FieldPackageVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(auditevent.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(auditevent.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(auditevent.FieldDetail, field.TypeString, value)
	}
	_node = &AuditEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
