// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dudebehinddude/aurforge/ent/auditevent"
)

// AuditEventCreate is the builder for creating a AuditEvent entity.
type AuditEventCreate struct {
	config
	mutation *AuditEventMutation
	hooks    []Hook
}

// SetPackageVersionID sets the "package_version_id" field.
func (_c *AuditEventCreate) SetPackageVersionID(v int64) *AuditEventCreate {
	_c.mutation.SetPackageVersionID(v)
	return _c
}

// SetSeverity sets the "severity" field.
func (_c *AuditEventCreate) SetSeverity(v string) *AuditEventCreate {
	_c.mutation.SetSeverity(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *AuditEventCreate) SetCode(v string) *AuditEventCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetDetail sets the "detail" field.
func (_c *AuditEventCreate) SetDetail(v string) *AuditEventCreate {
	_c.mutation.SetDetail(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuditEventCreate) SetCreatedAt(v time.Time) *AuditEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// Mutation returns the AuditEventMutation object of the builder.
func (_c *AuditEventCreate) Mutation() *AuditEventMutation {
	return _c.mutation
}

// Save creates the AuditEvent in the database.
func (_c *AuditEventCreate) Save(ctx context.Context) (*AuditEvent, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditEventCreate) SaveX(ctx context.Context) *AuditEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditEventCreate) check() error {
	if _, ok := _c.mutation.PackageVersionID(); !ok {
		return &ValidationError{Name: "package_version_id", err: errors.New(`ent: missing required field "AuditEvent.package_version_id"`)}
	}
	if _, ok := _c.mutation.Severity(); !ok {
		return &ValidationError{Name: "severity", err: errors.New(`ent: missing required field "AuditEvent.severity"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "AuditEvent.code"`)}
	}
	if _, ok := _c.mutation.Detail(); !ok {
		return &ValidationError{Name: "detail", err: errors.New(`ent: missing required field "AuditEvent.detail"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuditEvent.created_at"`)}
	}
	return nil
}

func (_c *AuditEventCreate) sqlSave(ctx context.Context) (*AuditEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditEventCreate) createSpec() (*AuditEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditevent.Table, sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.PackageVersionID(); ok {
		_spec.SetField(auditevent.FieldPackageVersionID, field.TypeInt64, value)
		_node.PackageVersionID = value
	}
	if value, ok := _c.mutation.Severity(); ok {
		_spec.SetField(auditevent.FieldSeverity, field.TypeString, value)
		_node.Severity = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(auditevent.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Detail(); ok {
		_spec.SetField(auditevent.FieldDetail, field.TypeString, value)
		_node.Detail = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(auditevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// AuditEventCreateBulk is the builder for creating many AuditEvent entities in bulk.
type AuditEventCreateBulk struct {
	config
	err      error
	builders []*AuditEventCreate
}

// Save creates the AuditEvent entities in the database.
func (_c *AuditEventCreateBulk) Save(ctx context.Context) ([]*AuditEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditEventCreateBulk) SaveX(ctx context.Context) []*AuditEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
