// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dudebehinddude/aurforge/ent/dependency"
	"github.com/dudebehinddude/aurforge/ent/predicate"
)

// DependencyUpdate is the builder for updating Dependency entities.
type DependencyUpdate struct {
	config
	hooks    []Hook
	mutation *DependencyMutation
}

// Where appends a list predicates to the DependencyUpdate builder.
func (_u *DependencyUpdate) Where(ps ...predicate.Dependency) *DependencyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPackageVersionID sets the "package_version_id" field.
func (_u *DependencyUpdate) SetPackageVersionID(v int64) *DependencyUpdate {
	_u.mutation.ResetPackageVersionID()
	_u.mutation.SetPackageVersionID(v)
	return _u
}

// SetNillablePackageVersionID sets the "package_version_id" field if the given value is not nil.
func (_u *DependencyUpdate) SetNillablePackageVersionID(v *int64) *DependencyUpdate {
	if v != nil {
		_u.SetPackageVersionID(*v)
	}
	return _u
}

// AddPackageVersionID adds value to the "package_version_id" field.
func (_u *DependencyUpdate) AddPackageVersionID(v int64) *DependencyUpdate {
	_u.mutation.AddPackageVersionID(v)
	return _u
}

// SetDependencyName sets the "dependency_name" field.
func (_u *DependencyUpdate) SetDependencyName(v string) *DependencyUpdate {
	_u.mutation.SetDependencyName(v)
	return _u
}

// SetNillableDependencyName sets the "dependency_name" field if the given value is not nil.
func (_u *DependencyUpdate) SetNillableDependencyName(v *string) *DependencyUpdate {
	if v != nil {
		_u.SetDependencyName(*v)
	}
	return _u
}

// SetDependencyKind sets the "dependency_kind" field.
func (_u *DependencyUpdate) SetDependencyKind(v dependency.DependencyKind) *DependencyUpdate {
	_u.mutation.SetDependencyKind(v)
	return _u
}

// SetNillableDependencyKind sets the "dependency_kind" field if the given value is not nil.
func (_u *DependencyUpdate) SetNillableDependencyKind(v *dependency.DependencyKind) *DependencyUpdate {
	if v != nil {
		_u.SetDependencyKind(*v)
	}
	return _u
}

// Mutation returns the DependencyMutation object of the builder.
func (_u *DependencyUpdate) Mutation() *DependencyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DependencyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DependencyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DependencyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DependencyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DependencyUpdate) check() error {
	if v, ok := _u.mutation.DependencyKind(); ok {
		if err := dependency.DependencyKindValidator(v); err != nil {
			return &ValidationError{Name: "dependency_kind", err: fmt.Errorf(`ent: validator failed for field "Dependency.dependency_kind": %w`, err)}
		}
	}
	return nil
}

func (_u *DependencyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dependency.Table, dependency.Columns, sqlgraph.NewFieldSpec(dependency.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PackageVersionID(); ok {
		_spec.SetField(dependency.FieldPackageVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPackageVersionID(); ok {
		_spec.AddField(dependency.FieldPackageVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DependencyName(); ok {
		_spec.SetField(dependency.FieldDependencyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DependencyKind(); ok {
		_spec.SetField(dependency.FieldDependencyKind, field.TypeEnum, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dependency.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DependencyUpdateOne is the builder for updating a single Dependency entity.
type DependencyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DependencyMutation
}

// SetPackageVersionID sets the "package_version_id" field.
func (_u *DependencyUpdateOne) SetPackageVersionID(v int64) *DependencyUpdateOne {
	_u.mutation.ResetPackageVersionID()
	_u.mutation.SetPackageVersionID(v)
	return _u
}

// SetNillablePackageVersionID sets the "package_version_id" field if the given value is not nil.
func (_u *DependencyUpdateOne) SetNillablePackageVersionID(v *int64) *DependencyUpdateOne {
	if v != nil {
		_u.SetPackageVersionID(*v)
	}
	return _u
}

// AddPackageVersionID adds value to the "package_version_id" field.
func (_u *DependencyUpdateOne) AddPackageVersionID(v int64) *DependencyUpdateOne {
	_u.mutation.AddPackageVersionID(v)
	return _u
}

// SetDependencyName sets the "dependency_name" field.
func (_u *DependencyUpdateOne) SetDependencyName(v string) *DependencyUpdateOne {
	_u.mutation.SetDependencyName(v)
	return _u
}

// SetNillableDependencyName sets the "dependency_name" field if the given value is not nil.
func (_u *DependencyUpdateOne) SetNillableDependencyName(v *string) *DependencyUpdateOne {
	if v != nil {
		_u.SetDependencyName(*v)
	}
	return _u
}

// SetDependencyKind sets the "dependency_kind" field.
func (_u *DependencyUpdateOne) SetDependencyKind(v dependency.DependencyKind) *DependencyUpdateOne {
	_u.mutation.SetDependencyKind(v)
	return _u
}

// SetNillableDependencyKind sets the "dependency_kind" field if the given value is not nil.
func (_u *DependencyUpdateOne) SetNillableDependencyKind(v *dependency.DependencyKind) *DependencyUpdateOne {
	if v != nil {
		_u.SetDependencyKind(*v)
	}
	return _u
}

// Mutation returns the DependencyMutation object of the builder.
func (_u *DependencyUpdateOne) Mutation() *DependencyMutation {
	return _u.mutation
}

// Where appends a list predicates to the DependencyUpdate builder.
func (_u *DependencyUpdateOne) Where(ps ...predicate.Dependency) *DependencyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DependencyUpdateOne) Select(field string, fields ...string) *DependencyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Dependency entity.
func (_u *DependencyUpdateOne) Save(ctx context.Context) (*Dependency, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DependencyUpdateOne) SaveX(ctx context.Context) *Dependency {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DependencyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DependencyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DependencyUpdateOne) check() error {
	if v, ok := _u.mutation.DependencyKind(); ok {
		if err := dependency.DependencyKindValidator(v); err != nil {
			return &ValidationError{Name: "dependency_kind", err: fmt.Errorf(`ent: validator failed for field "Dependency.dependency_kind": %w`, err)}
		}
	}
	return nil
}

func (_u *DependencyUpdateOne) sqlSave(ctx context.Context) (_node *Dependency, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dependency.Table, dependency.Columns, sqlgraph.NewFieldSpec(dependency.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Dependency.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dependency.FieldID)
		for _, f := range fields {
			if !dependency.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dependency.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PackageVersionID(); ok {
		_spec.SetField(dependency.FieldPackageVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPackageVersionID(); ok {
		_spec.AddField(dependency.FieldPackageVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DependencyName(); ok {
		_spec.SetField(dependency.FieldDependencyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.DependencyKind(); ok {
		_spec.SetField(dependency.FieldDependencyKind, field.TypeEnum, value)
	}
	_node = &Dependency{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dependency.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
