// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dudebehinddude/aurforge/ent/dependency"
)

// Dependency is the model entity for the Dependency schema.
type Dependency struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PackageVersionID holds the value of the "package_version_id" field.
	PackageVersionID int64 `json:"package_version_id,omitempty"`
	// DependencyName holds the value of the "dependency_name" field.
	DependencyName string `json:"dependency_name,omitempty"`
	// DependencyKind holds the value of the "dependency_kind" field.
	DependencyKind dependency.DependencyKind `json:"dependency_kind,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Dependency) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dependency.FieldID, dependency.FieldPackageVersionID:
			values[i] = new(sql.NullInt64)
		case dependency.FieldDependencyName, dependency.FieldDependencyKind:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Dependency fields.
func (_m *Dependency) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dependency.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case dependency.FieldPackageVersionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field package_version_id", values[i])
			} else if value.Valid {
				_m.PackageVersionID = value.Int64
			}
		case dependency.FieldDependencyName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dependency_name", values[i])
			} else if value.Valid {
				_m.DependencyName = value.String
			}
		case dependency.FieldDependencyKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dependency_kind", values[i])
			} else if value.Valid {
				_m.DependencyKind = dependency.DependencyKind(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Dependency.
// This includes values selected through modifiers, order, etc.
func (_m *Dependency) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Dependency.
// Note that you need to call Dependency.Unwrap() before calling this method if this Dependency
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Dependency) Update() *DependencyUpdateOne {
	return NewDependencyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Dependency entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Dependency) Unwrap() *Dependency {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Dependency is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Dependency) String() string {
	var builder strings.Builder
	builder.WriteString("Dependency(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("package_version_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PackageVersionID))
	builder.WriteString(", ")
	builder.WriteString("dependency_name=")
	builder.WriteString(_m.DependencyName)
	builder.WriteString(", ")
	builder.WriteString("dependency_kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.DependencyKind))
	builder.WriteByte(')')
	return builder.String()
}

// Dependencies is a parsable slice of Dependency.
type Dependencies []*Dependency
