// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dudebehinddude/aurforge/ent/job"
)

// JobCreate is the builder for creating a Job entity.
type JobCreate struct {
	config
	mutation *JobMutation
	hooks    []Hook
}

// SetPackageVersionID sets the "package_version_id" field.
func (_c *JobCreate) SetPackageVersionID(v int64) *JobCreate {
	_c.mutation.SetPackageVersionID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *JobCreate) SetKind(v string) *JobCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_c *JobCreate) SetNillableKind(v *string) *JobCreate {
	if v != nil {
		_c.SetKind(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *JobCreate) SetStatus(v job.Status) *JobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *JobCreate) SetNillableStatus(v *job.Status) *JobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetEligibleAt sets the "eligible_at" field.
func (_c *JobCreate) SetEligibleAt(v time.Time) *JobCreate {
	_c.mutation.SetEligibleAt(v)
	return _c
}

// SetClaimedAt sets the "claimed_at" field.
func (_c *JobCreate) SetClaimedAt(v time.Time) *JobCreate {
	_c.mutation.SetClaimedAt(v)
	return _c
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_c *JobCreate) SetNillableClaimedAt(v *time.Time) *JobCreate {
	if v != nil {
		_c.SetClaimedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *JobCreate) SetFinishedAt(v time.Time) *JobCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *JobCreate) SetNillableFinishedAt(v *time.Time) *JobCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *JobCreate) SetAttempts(v int) *JobCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *JobCreate) SetNillableAttempts(v *int) *JobCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetLogPath sets the "log_path" field.
func (_c *JobCreate) SetLogPath(v string) *JobCreate {
	_c.mutation.SetLogPath(v)
	return _c
}

// SetNillableLogPath sets the "log_path" field if the given value is not nil.
func (_c *JobCreate) SetNillableLogPath(v *string) *JobCreate {
	if v != nil {
		_c.SetLogPath(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *JobCreate) SetError(v string) *JobCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *JobCreate) SetNillableError(v *string) *JobCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *JobCreate) SetCreatedAt(v time.Time) *JobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// Mutation returns the JobMutation object of the builder.
func (_c *JobCreate) Mutation() *JobMutation {
	return _c.mutation
}

// Save creates the Job in the database.
func (_c *JobCreate) Save(ctx context.Context) (*Job, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *JobCreate) SaveX(ctx context.Context) *Job {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *JobCreate) defaults() {
	if _, ok := _c.mutation.Kind(); !ok {
		v := job.DefaultKind
		_c.mutation.SetKind(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := job.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := job.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *JobCreate) check() error {
	if _, ok := _c.mutation.PackageVersionID(); !ok {
		return &ValidationError{Name: "package_version_id", err: errors.New(`ent: missing required field "Job.package_version_id"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Job.kind"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Job.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := job.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Job.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EligibleAt(); !ok {
		return &ValidationError{Name: "eligible_at", err: errors.New(`ent: missing required field "Job.eligible_at"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "Job.attempts"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Job.created_at"`)}
	}
	return nil
}

func (_c *JobCreate) sqlSave(ctx context.Context) (*Job, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *JobCreate) createSpec() (*Job, *sqlgraph.CreateSpec) {
	var (
		_node = &Job{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(job.Table, sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.PackageVersionID(); ok {
		_spec.SetField(job.FieldPackageVersionID, field.TypeInt64, value)
		_node.PackageVersionID = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(job.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.EligibleAt(); ok {
		_spec.SetField(job.FieldEligibleAt, field.TypeTime, value)
		_node.EligibleAt = value
	}
	if value, ok := _c.mutation.ClaimedAt(); ok {
		_spec.SetField(job.FieldClaimedAt, field.TypeTime, value)
		_node.ClaimedAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(job.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(job.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.LogPath(); ok {
		_spec.SetField(job.FieldLogPath, field.TypeString, value)
		_node.LogPath = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(job.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(job.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// JobCreateBulk is the builder for creating many Job entities in bulk.
type JobCreateBulk struct {
	config
	err      error
	builders []*JobCreate
}

// Save creates the Job entities in the database.
func (_c *JobCreateBulk) Save(ctx context.Context) ([]*Job, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Job, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *JobCreateBulk) SaveX(ctx context.Context) []*Job {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
