// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dudebehinddude/aurforge/ent/job"
	"github.com/dudebehinddude/aurforge/ent/predicate"
)

// JobUpdate is the builder for updating Job entities.
type JobUpdate struct {
	config
	hooks    []Hook
	mutation *JobMutation
}

// Where appends a list predicates to the JobUpdate builder.
func (_u *JobUpdate) Where(ps ...predicate.Job) *JobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPackageVersionID sets the "package_version_id" field.
func (_u *JobUpdate) SetPackageVersionID(v int64) *JobUpdate {
	_u.mutation.ResetPackageVersionID()
	_u.mutation.SetPackageVersionID(v)
	return _u
}

// SetNillablePackageVersionID sets the "package_version_id" field if the given value is not nil.
func (_u *JobUpdate) SetNillablePackageVersionID(v *int64) *JobUpdate {
	if v != nil {
		_u.SetPackageVersionID(*v)
	}
	return _u
}

// AddPackageVersionID adds value to the "package_version_id" field.
func (_u *JobUpdate) AddPackageVersionID(v int64) *JobUpdate {
	_u.mutation.AddPackageVersionID(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *JobUpdate) SetKind(v string) *JobUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *JobUpdate) SetNillableKind(v *string) *JobUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *JobUpdate) SetStatus(v job.Status) *JobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *JobUpdate) SetNillableStatus(v *job.Status) *JobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEligibleAt sets the "eligible_at" field.
func (_u *JobUpdate) SetEligibleAt(v time.Time) *JobUpdate {
	_u.mutation.SetEligibleAt(v)
	return _u
}

// SetNillableEligibleAt sets the "eligible_at" field if the given value is not nil.
func (_u *JobUpdate) SetNillableEligibleAt(v *time.Time) *JobUpdate {
	if v != nil {
		_u.SetEligibleAt(*v)
	}
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *JobUpdate) SetClaimedAt(v time.Time) *JobUpdate {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *JobUpdate) SetNillableClaimedAt(v *time.Time) *JobUpdate {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (_u *JobUpdate) ClearClaimedAt() *JobUpdate {
	_u.mutation.ClearClaimedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *JobUpdate) SetFinishedAt(v time.Time) *JobUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *JobUpdate) SetNillableFinishedAt(v *time.Time) *JobUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *JobUpdate) ClearFinishedAt() *JobUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *JobUpdate) SetAttempts(v int) *JobUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *JobUpdate) SetNillableAttempts(v *int) *JobUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *JobUpdate) AddAttempts(v int) *JobUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetLogPath sets the "log_path" field.
func (_u *JobUpdate) SetLogPath(v string) *JobUpdate {
	_u.mutation.SetLogPath(v)
	return _u
}

// SetNillableLogPath sets the "log_path" field if the given value is not nil.
func (_u *JobUpdate) SetNillableLogPath(v *string) *JobUpdate {
	if v != nil {
		_u.SetLogPath(*v)
	}
	return _u
}

// ClearLogPath clears the value of the "log_path" field.
func (_u *JobUpdate) ClearLogPath() *JobUpdate {
	_u.mutation.ClearLogPath()
	return _u
}

// SetError sets the "error" field.
func (_u *JobUpdate) SetError(v string) *JobUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *JobUpdate) SetNillableError(v *string) *JobUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *JobUpdate) ClearError() *JobUpdate {
	_u.mutation.ClearError()
	return _u
}

// Mutation returns the JobMutation object of the builder.
func (_u *JobUpdate) Mutation() *JobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *JobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *JobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JobUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := job.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Job.status": %w`, err)}
		}
	}
	return nil
}

func (_u *JobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PackageVersionID(); ok {
		_spec.SetField(job.FieldPackageVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPackageVersionID(); ok {
		_spec.AddField(job.FieldPackageVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(job.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EligibleAt(); ok {
		_spec.SetField(job.FieldEligibleAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(job.FieldClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.ClaimedAtCleared() {
		_spec.ClearField(job.FieldClaimedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(job.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(job.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(job.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(job.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LogPath(); ok {
		_spec.SetField(job.FieldLogPath, field.TypeString, value)
	}
	if _u.mutation.LogPathCleared() {
		_spec.ClearField(job.FieldLogPath, field.TypeString)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(job.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(job.FieldError, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// JobUpdateOne is the builder for updating a single Job entity.
type JobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobMutation
}

// SetPackageVersionID sets the "package_version_id" field.
func (_u *JobUpdateOne) SetPackageVersionID(v int64) *JobUpdateOne {
	_u.mutation.ResetPackageVersionID()
	_u.mutation.SetPackageVersionID(v)
	return _u
}

// SetNillablePackageVersionID sets the "package_version_id" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillablePackageVersionID(v *int64) *JobUpdateOne {
	if v != nil {
		_u.SetPackageVersionID(*v)
	}
	return _u
}

// AddPackageVersionID adds value to the "package_version_id" field.
func (_u *JobUpdateOne) AddPackageVersionID(v int64) *JobUpdateOne {
	_u.mutation.AddPackageVersionID(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *JobUpdateOne) SetKind(v string) *JobUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableKind(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *JobUpdateOne) SetStatus(v job.Status) *JobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableStatus(v *job.Status) *JobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEligibleAt sets the "eligible_at" field.
func (_u *JobUpdateOne) SetEligibleAt(v time.Time) *JobUpdateOne {
	_u.mutation.SetEligibleAt(v)
	return _u
}

// SetNillableEligibleAt sets the "eligible_at" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableEligibleAt(v *time.Time) *JobUpdateOne {
	if v != nil {
		_u.SetEligibleAt(*v)
	}
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *JobUpdateOne) SetClaimedAt(v time.Time) *JobUpdateOne {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableClaimedAt(v *time.Time) *JobUpdateOne {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (_u *JobUpdateOne) ClearClaimedAt() *JobUpdateOne {
	_u.mutation.ClearClaimedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *JobUpdateOne) SetFinishedAt(v time.Time) *JobUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableFinishedAt(v *time.Time) *JobUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *JobUpdateOne) ClearFinishedAt() *JobUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *JobUpdateOne) SetAttempts(v int) *JobUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableAttempts(v *int) *JobUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *JobUpdateOne) AddAttempts(v int) *JobUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetLogPath sets the "log_path" field.
func (_u *JobUpdateOne) SetLogPath(v string) *JobUpdateOne {
	_u.mutation.SetLogPath(v)
	return _u
}

// SetNillableLogPath sets the "log_path" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableLogPath(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetLogPath(*v)
	}
	return _u
}

// ClearLogPath clears the value of the "log_path" field.
func (_u *JobUpdateOne) ClearLogPath() *JobUpdateOne {
	_u.mutation.ClearLogPath()
	return _u
}

// SetError sets the "error" field.
func (_u *JobUpdateOne) SetError(v string) *JobUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableError(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *JobUpdateOne) ClearError() *JobUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// Mutation returns the JobMutation object of the builder.
func (_u *JobUpdateOne) Mutation() *JobMutation {
	return _u.mutation
}

// Where appends a list predicates to the JobUpdate builder.
func (_u *JobUpdateOne) Where(ps ...predicate.Job) *JobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *JobUpdateOne) Select(field string, fields ...string) *JobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Job entity.
func (_u *JobUpdateOne) Save(ctx context.Context) (*Job, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobUpdateOne) SaveX(ctx context.Context) *Job {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *JobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JobUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := job.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Job.status": %w`, err)}
		}
	}
	return nil
}

func (_u *JobUpdateOne) sqlSave(ctx context.Context) (_node *Job, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Job.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, job.FieldID)
		for _, f := range fields {
			if !job.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != job.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PackageVersionID(); ok {
		_spec.SetField(job.FieldPackageVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPackageVersionID(); ok {
		_spec.AddField(job.FieldPackageVersionID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(job.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EligibleAt(); ok {
		_spec.SetField(job.FieldEligibleAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(job.FieldClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.ClaimedAtCleared() {
		_spec.ClearField(job.FieldClaimedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(job.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(job.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(job.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(job.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LogPath(); ok {
		_spec.SetField(job.FieldLogPath, field.TypeString, value)
	}
	if _u.mutation.LogPathCleared() {
		_spec.ClearField(job.FieldLogPath, field.TypeString)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(job.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(job.FieldError, field.TypeString)
	}
	_node = &Job{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
