// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dudebehinddude/aurforge/ent/managedpackage"
)

// ManagedPackageCreate is the builder for creating a ManagedPackage entity.
type ManagedPackageCreate struct {
	config
	mutation *ManagedPackageMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ManagedPackageCreate) SetName(v string) *ManagedPackageCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSourceKind sets the "source_kind" field.
func (_c *ManagedPackageCreate) SetSourceKind(v managedpackage.SourceKind) *ManagedPackageCreate {
	_c.mutation.SetSourceKind(v)
	return _c
}

// SetSourceRef sets the "source_ref" field.
func (_c *ManagedPackageCreate) SetSourceRef(v string) *ManagedPackageCreate {
	_c.mutation.SetSourceRef(v)
	return _c
}

// SetSourcePath sets the "source_path" field.
func (_c *ManagedPackageCreate) SetSourcePath(v string) *ManagedPackageCreate {
	_c.mutation.SetSourcePath(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ManagedPackageCreate) SetEnabled(v bool) *ManagedPackageCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ManagedPackageCreate) SetNillableEnabled(v *bool) *ManagedPackageCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ManagedPackageCreate) SetCreatedAt(v time.Time) *ManagedPackageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ManagedPackageCreate) SetUpdatedAt(v time.Time) *ManagedPackageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// Mutation returns the ManagedPackageMutation object of the builder.
func (_c *ManagedPackageCreate) Mutation() *ManagedPackageMutation {
	return _c.mutation
}

// Save creates the ManagedPackage in the database.
func (_c *ManagedPackageCreate) Save(ctx context.Context) (*ManagedPackage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ManagedPackageCreate) SaveX(ctx context.Context) *ManagedPackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ManagedPackageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ManagedPackageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ManagedPackageCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := managedpackage.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ManagedPackageCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ManagedPackage.name"`)}
	}
	if _, ok := _c.mutation.SourceKind(); !ok {
		return &ValidationError{Name: "source_kind", err: errors.New(`ent: missing required field "ManagedPackage.source_kind"`)}
	}
	if v, ok := _c.mutation.SourceKind(); ok {
		if err := managedpackage.SourceKindValidator(v); err != nil {
			return &ValidationError{Name: "source_kind", err: fmt.Errorf(`ent: validator failed for field "ManagedPackage.source_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceRef(); !ok {
		return &ValidationError{Name: "source_ref", err: errors.New(`ent: missing required field "ManagedPackage.source_ref"`)}
	}
	if _, ok := _c.mutation.SourcePath(); !ok {
		return &ValidationError{Name: "source_path", err: errors.New(`ent: missing required field "ManagedPackage.source_path"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ManagedPackage.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ManagedPackage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ManagedPackage.updated_at"`)}
	}
	return nil
}

func (_c *ManagedPackageCreate) sqlSave(ctx context.Context) (*ManagedPackage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ManagedPackageCreate) createSpec() (*ManagedPackage, *sqlgraph.CreateSpec) {
	var (
		_node = &ManagedPackage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(managedpackage.Table, sqlgraph.NewFieldSpec(managedpackage.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(managedpackage.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.SourceKind(); ok {
		_spec.SetField(managedpackage.FieldSourceKind, field.TypeEnum, value)
		_node.SourceKind = value
	}
	if value, ok := _c.mutation.SourceRef(); ok {
		_spec.SetField(managedpackage.FieldSourceRef, field.TypeString, value)
		_node.SourceRef = value
	}
	if value, ok := _c.mutation.SourcePath(); ok {
		_spec.SetField(managedpackage.FieldSourcePath, field.TypeString, value)
		_node.SourcePath = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(managedpackage.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(managedpackage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(managedpackage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ManagedPackageCreateBulk is the builder for creating many ManagedPackage entities in bulk.
type ManagedPackageCreateBulk struct {
	config
	err      error
	builders []*ManagedPackageCreate
}

// Save creates the ManagedPackage entities in the database.
func (_c *ManagedPackageCreateBulk) Save(ctx context.Context) ([]*ManagedPackage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ManagedPackage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ManagedPackageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ManagedPackageCreateBulk) SaveX(ctx context.Context) []*ManagedPackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ManagedPackageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ManagedPackageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
