// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dudebehinddude/aurforge/ent/managedpackage"
	"github.com/dudebehinddude/aurforge/ent/predicate"
)

// ManagedPackageUpdate is the builder for updating ManagedPackage entities.
type ManagedPackageUpdate struct {
	config
	hooks    []Hook
	mutation *ManagedPackageMutation
}

// Where appends a list predicates to the ManagedPackageUpdate builder.
func (_u *ManagedPackageUpdate) Where(ps ...predicate.ManagedPackage) *ManagedPackageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ManagedPackageUpdate) SetName(v string) *ManagedPackageUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ManagedPackageUpdate) SetNillableName(v *string) *ManagedPackageUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSourceKind sets the "source_kind" field.
func (_u *ManagedPackageUpdate) SetSourceKind(v managedpackage.SourceKind) *ManagedPackageUpdate {
	_u.mutation.SetSourceKind(v)
	return _u
}

// SetNillableSourceKind sets the "source_kind" field if the given value is not nil.
func (_u *ManagedPackageUpdate) SetNillableSourceKind(v *managedpackage.SourceKind) *ManagedPackageUpdate {
	if v != nil {
		_u.SetSourceKind(*v)
	}
	return _u
}

// SetSourceRef sets the "source_ref" field.
func (_u *ManagedPackageUpdate) SetSourceRef(v string) *ManagedPackageUpdate {
	_u.mutation.SetSourceRef(v)
	return _u
}

// SetNillableSourceRef sets the "source_ref" field if the given value is not nil.
func (_u *ManagedPackageUpdate) SetNillableSourceRef(v *string) *ManagedPackageUpdate {
	if v != nil {
		_u.SetSourceRef(*v)
	}
	return _u
}

// SetSourcePath sets the "source_path" field.
func (_u *ManagedPackageUpdate) SetSourcePath(v string) *ManagedPackageUpdate {
	_u.mutation.SetSourcePath(v)
	return _u
}

// SetNillableSourcePath sets the "source_path" field if the given value is not nil.
func (_u *ManagedPackageUpdate) SetNillableSourcePath(v *string) *ManagedPackageUpdate {
	if v != nil {
		_u.SetSourcePath(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ManagedPackageUpdate) SetEnabled(v bool) *ManagedPackageUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ManagedPackageUpdate) SetNillableEnabled(v *bool) *ManagedPackageUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ManagedPackageUpdate) SetUpdatedAt(v time.Time) *ManagedPackageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ManagedPackageMutation object of the builder.
func (_u *ManagedPackageUpdate) Mutation() *ManagedPackageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ManagedPackageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ManagedPackageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ManagedPackageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ManagedPackageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ManagedPackageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := managedpackage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ManagedPackageUpdate) check() error {
	if v, ok := _u.mutation.SourceKind(); ok {
		if err := managedpackage.SourceKindValidator(v); err != nil {
			return &ValidationError{Name: "source_kind", err: fmt.Errorf(`ent: validator failed for field "ManagedPackage.source_kind": %w`, err)}
		}
	}
	return nil
}

func (_u *ManagedPackageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(managedpackage.Table, managedpackage.Columns, sqlgraph.NewFieldSpec(managedpackage.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(managedpackage.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceKind(); ok {
		_spec.SetField(managedpackage.FieldSourceKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SourceRef(); ok {
		_spec.SetField(managedpackage.FieldSourceRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourcePath(); ok {
		_spec.SetField(managedpackage.FieldSourcePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(managedpackage.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(managedpackage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{managedpackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ManagedPackageUpdateOne is the builder for updating a single ManagedPackage entity.
type ManagedPackageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ManagedPackageMutation
}

// SetName sets the "name" field.
func (_u *ManagedPackageUpdateOne) SetName(v string) *ManagedPackageUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ManagedPackageUpdateOne) SetNillableName(v *string) *ManagedPackageUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSourceKind sets the "source_kind" field.
func (_u *ManagedPackageUpdateOne) SetSourceKind(v managedpackage.SourceKind) *ManagedPackageUpdateOne {
	_u.mutation.SetSourceKind(v)
	return _u
}

// SetNillableSourceKind sets the "source_kind" field if the given value is not nil.
func (_u *ManagedPackageUpdateOne) SetNillableSourceKind(v *managedpackage.SourceKind) *ManagedPackageUpdateOne {
	if v != nil {
		_u.SetSourceKind(*v)
	}
	return _u
}

// SetSourceRef sets the "source_ref" field.
func (_u *ManagedPackageUpdateOne) SetSourceRef(v string) *ManagedPackageUpdateOne {
	_u.mutation.SetSourceRef(v)
	return _u
}

// SetNillableSourceRef sets the "source_ref" field if the given value is not nil.
func (_u *ManagedPackageUpdateOne) SetNillableSourceRef(v *string) *ManagedPackageUpdateOne {
	if v != nil {
		_u.SetSourceRef(*v)
	}
	return _u
}

// SetSourcePath sets the "source_path" field.
func (_u *ManagedPackageUpdateOne) SetSourcePath(v string) *ManagedPackageUpdateOne {
	_u.mutation.SetSourcePath(v)
	return _u
}

// SetNillableSourcePath sets the "source_path" field if the given value is not nil.
func (_u *ManagedPackageUpdateOne) SetNillableSourcePath(v *string) *ManagedPackageUpdateOne {
	if v != nil {
		_u.SetSourcePath(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ManagedPackageUpdateOne) SetEnabled(v bool) *ManagedPackageUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ManagedPackageUpdateOne) SetNillableEnabled(v *bool) *ManagedPackageUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ManagedPackageUpdateOne) SetUpdatedAt(v time.Time) *ManagedPackageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ManagedPackageMutation object of the builder.
func (_u *ManagedPackageUpdateOne) Mutation() *ManagedPackageMutation {
	return _u.mutation
}

// Where appends a list predicates to the ManagedPackageUpdate builder.
func (_u *ManagedPackageUpdateOne) Where(ps ...predicate.ManagedPackage) *ManagedPackageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ManagedPackageUpdateOne) Select(field string, fields ...string) *ManagedPackageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ManagedPackage entity.
func (_u *ManagedPackageUpdateOne) Save(ctx context.Context) (*ManagedPackage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ManagedPackageUpdateOne) SaveX(ctx context.Context) *ManagedPackage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ManagedPackageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ManagedPackageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ManagedPackageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := managedpackage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ManagedPackageUpdateOne) check() error {
	if v, ok := _u.mutation.SourceKind(); ok {
		if err := managedpackage.SourceKindValidator(v); err != nil {
			return &ValidationError{Name: "source_kind", err: fmt.Errorf(`ent: validator failed for field "ManagedPackage.source_kind": %w`, err)}
		}
	}
	return nil
}

func (_u *ManagedPackageUpdateOne) sqlSave(ctx context.Context) (_node *ManagedPackage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(managedpackage.Table, managedpackage.Columns, sqlgraph.NewFieldSpec(managedpackage.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ManagedPackage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, managedpackage.FieldID)
		for _, f := range fields {
			if !managedpackage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != managedpackage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(managedpackage.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceKind(); ok {
		_spec.SetField(managedpackage.FieldSourceKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SourceRef(); ok {
		_spec.SetField(managedpackage.FieldSourceRef, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourcePath(); ok {
		_spec.SetField(managedpackage.FieldSourcePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(managedpackage.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(managedpackage.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ManagedPackage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{managedpackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
