// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dudebehinddude/aurforge/ent/managedpackage"
)

// ManagedPackage is the model entity for the ManagedPackage schema.
type ManagedPackage struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// SourceKind holds the value of the "source_kind" field.
	SourceKind managedpackage.SourceKind `json:"source_kind,omitempty"`
	// SourceRef holds the value of the "source_ref" field.
	SourceRef string `json:"source_ref,omitempty"`
	// SourcePath holds the value of the "source_path" field.
	SourcePath string `json:"source_path,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ManagedPackage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case managedpackage.FieldEnabled:
			values[i] = new(sql.NullBool)
		case managedpackage.FieldID:
			values[i] = new(sql.NullInt64)
		case managedpackage.FieldName, managedpackage.FieldSourceKind, managedpackage.FieldSourceRef, managedpackage.FieldSourcePath:
			values[i] = new(sql.NullString)
		case managedpackage.FieldCreatedAt, managedpackage.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ManagedPackage fields.
func (_m *ManagedPackage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case managedpackage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case managedpackage.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case managedpackage.FieldSourceKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_kind", values[i])
			} else if value.Valid {
				_m.SourceKind = managedpackage.SourceKind(value.String)
			}
		case managedpackage.FieldSourceRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_ref", values[i])
			} else if value.Valid {
				_m.SourceRef = value.String
			}
		case managedpackage.FieldSourcePath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_path", values[i])
			} else if value.Valid {
				_m.SourcePath = value.String
			}
		case managedpackage.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case managedpackage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case managedpackage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ManagedPackage.
// This includes values selected through modifiers, order, etc.
func (_m *ManagedPackage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ManagedPackage.
// Note that you need to call ManagedPackage.Unwrap() before calling this method if this ManagedPackage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ManagedPackage) Update() *ManagedPackageUpdateOne {
	return NewManagedPackageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ManagedPackage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ManagedPackage) Unwrap() *ManagedPackage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ManagedPackage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ManagedPackage) String() string {
	var builder strings.Builder
	builder.WriteString("ManagedPackage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("source_kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceKind))
	builder.WriteString(", ")
	builder.WriteString("source_ref=")
	builder.WriteString(_m.SourceRef)
	builder.WriteString(", ")
	builder.WriteString("source_path=")
	builder.WriteString(_m.SourcePath)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ManagedPackages is a parsable slice of ManagedPackage.
type ManagedPackages []*ManagedPackage
