// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dudebehinddude/aurforge/ent/packageversion"
)

// PackageVersionCreate is the builder for creating a PackageVersion entity.
type PackageVersionCreate struct {
	config
	mutation *PackageVersionMutation
	hooks    []Hook
}

// SetPackageID sets the "package_id" field.
func (_c *PackageVersionCreate) SetPackageID(v int64) *PackageVersionCreate {
	_c.mutation.SetPackageID(v)
	return _c
}

// SetRevision sets the "revision" field.
func (_c *PackageVersionCreate) SetRevision(v string) *PackageVersionCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetSourceDigest sets the "source_digest" field.
func (_c *PackageVersionCreate) SetSourceDigest(v string) *PackageVersionCreate {
	_c.mutation.SetSourceDigest(v)
	return _c
}

// SetPkgver sets the "pkgver" field.
func (_c *PackageVersionCreate) SetPkgver(v string) *PackageVersionCreate {
	_c.mutation.SetPkgver(v)
	return _c
}

// SetPkgrel sets the "pkgrel" field.
func (_c *PackageVersionCreate) SetPkgrel(v string) *PackageVersionCreate {
	_c.mutation.SetPkgrel(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *PackageVersionCreate) SetMetadata(v map[string]interface{}) *PackageVersionCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_c *PackageVersionCreate) SetFirstSeenAt(v time.Time) *PackageVersionCreate {
	_c.mutation.SetFirstSeenAt(v)
	return _c
}

// Mutation returns the PackageVersionMutation object of the builder.
func (_c *PackageVersionCreate) Mutation() *PackageVersionMutation {
	return _c.mutation
}

// Save creates the PackageVersion in the database.
func (_c *PackageVersionCreate) Save(ctx context.Context) (*PackageVersion, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PackageVersionCreate) SaveX(ctx context.Context) *PackageVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PackageVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PackageVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PackageVersionCreate) check() error {
	if _, ok := _c.mutation.PackageID(); !ok {
		return &ValidationError{Name: "package_id", err: errors.New(`ent: missing required field "PackageVersion.package_id"`)}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "PackageVersion.revision"`)}
	}
	if _, ok := _c.mutation.SourceDigest(); !ok {
		return &ValidationError{Name: "source_digest", err: errors.New(`ent: missing required field "PackageVersion.source_digest"`)}
	}
	if _, ok := _c.mutation.Pkgver(); !ok {
		return &ValidationError{Name: "pkgver", err: errors.New(`ent: missing required field "PackageVersion.pkgver"`)}
	}
	if _, ok := _c.mutation.Pkgrel(); !ok {
		return &ValidationError{Name: "pkgrel", err: errors.New(`ent: missing required field "PackageVersion.pkgrel"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "PackageVersion.metadata"`)}
	}
	if _, ok := _c.mutation.FirstSeenAt(); !ok {
		return &ValidationError{Name: "first_seen_at", err: errors.New(`ent: missing required field "PackageVersion.first_seen_at"`)}
	}
	return nil
}

func (_c *PackageVersionCreate) sqlSave(ctx context.Context) (*PackageVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PackageVersionCreate) createSpec() (*PackageVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &PackageVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(packageversion.Table, sqlgraph.NewFieldSpec(packageversion.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.PackageID(); ok {
		_spec.SetField(packageversion.FieldPackageID, field.TypeInt64, value)
		_node.PackageID = value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(packageversion.FieldRevision, field.TypeString, value)
		_node.Revision = value
	}
	if value, ok := _c.mutation.SourceDigest(); ok {
		_spec.SetField(packageversion.FieldSourceDigest, field.TypeString, value)
		_node.SourceDigest = value
	}
	if value, ok := _c.mutation.Pkgver(); ok {
		_spec.SetField(packageversion.FieldPkgver, field.TypeString, value)
		_node.Pkgver = value
	}
	if value, ok := _c.mutation.Pkgrel(); ok {
		_spec.SetField(packageversion.FieldPkgrel, field.TypeString, value)
		_node.Pkgrel = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(packageversion.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.FirstSeenAt(); ok {
		_spec.SetField(packageversion.FieldFirstSeenAt, field.TypeTime, value)
		_node.FirstSeenAt = value
	}
	return _node, _spec
}

// PackageVersionCreateBulk is the builder for creating many PackageVersion entities in bulk.
type PackageVersionCreateBulk struct {
	config
	err      error
	builders []*PackageVersionCreate
}

// Save creates the PackageVersion entities in the database.
func (_c *PackageVersionCreateBulk) Save(ctx context.Context) ([]*PackageVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PackageVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PackageVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PackageVersionCreateBulk) SaveX(ctx context.Context) []*PackageVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PackageVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PackageVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
