// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/dudebehinddude/aurforge/ent/packageversion"
)

// PackageVersion is the model entity for the PackageVersion schema.
type PackageVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PackageID holds the value of the "package_id" field.
	PackageID int64 `json:"package_id,omitempty"`
	// Revision holds the value of the "revision" field.
	Revision string `json:"revision,omitempty"`
	// SourceDigest holds the value of the "source_digest" field.
	SourceDigest string `json:"source_digest,omitempty"`
	// Pkgver holds the value of the "pkgver" field.
	Pkgver string `json:"pkgver,omitempty"`
	// Pkgrel holds the value of the "pkgrel" field.
	Pkgrel string `json:"pkgrel,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// FirstSeenAt holds the value of the "first_seen_at" field.
	FirstSeenAt  time.Time `json:"first_seen_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PackageVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case packageversion.FieldMetadata:
			values[i] = new([]byte)
		case packageversion.FieldID, packageversion.FieldPackageID:
			values[i] = new(sql.NullInt64)
		case packageversion.FieldRevision, packageversion.FieldSourceDigest, packageversion.FieldPkgver, packageversion.FieldPkgrel:
			values[i] = new(sql.NullString)
		case packageversion.FieldFirstSeenAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PackageVersion fields.
func (_m *PackageVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case packageversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case packageversion.FieldPackageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field package_id", values[i])
			} else if value.Valid {
				_m.PackageID = value.Int64
			}
		case packageversion.FieldRevision:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				_m.Revision = value.String
			}
		case packageversion.FieldSourceDigest:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_digest", values[i])
			} else if value.Valid {
				_m.SourceDigest = value.String
			}
		case packageversion.FieldPkgver:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pkgver", values[i])
			} else if value.Valid {
				_m.Pkgver = value.String
			}
		case packageversion.FieldPkgrel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pkgrel", values[i])
			} else if value.Valid {
				_m.Pkgrel = value.String
			}
		case packageversion.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case packageversion.FieldFirstSeenAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field first_seen_at", values[i])
			} else if value.Valid {
				_m.FirstSeenAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PackageVersion.
// This includes values selected through modifiers, order, etc.
func (_m *PackageVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PackageVersion.
// Note that you need to call PackageVersion.Unwrap() before calling this method if this PackageVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PackageVersion) Update() *PackageVersionUpdateOne {
	return NewPackageVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PackageVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PackageVersion) Unwrap() *PackageVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PackageVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PackageVersion) String() string {
	var builder strings.Builder
	builder.WriteString("PackageVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("package_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PackageID))
	builder.WriteString(", ")
	builder.WriteString("revision=")
	builder.WriteString(_m.Revision)
	builder.WriteString(", ")
	builder.WriteString("source_digest=")
	builder.WriteString(_m.SourceDigest)
	builder.WriteString(", ")
	builder.WriteString("pkgver=")
	builder.WriteString(_m.Pkgver)
	builder.WriteString(", ")
	builder.WriteString("pkgrel=")
	builder.WriteString(_m.Pkgrel)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("first_seen_at=")
	builder.WriteString(_m.FirstSeenAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PackageVersions is a parsable slice of PackageVersion.
type PackageVersions []*PackageVersion
