// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dudebehinddude/aurforge/ent/packageversion"
	"github.com/dudebehinddude/aurforge/ent/predicate"
)

// PackageVersionUpdate is the builder for updating PackageVersion entities.
type PackageVersionUpdate struct {
	config
	hooks    []Hook
	mutation *PackageVersionMutation
}

// Where appends a list predicates to the PackageVersionUpdate builder.
func (_u *PackageVersionUpdate) Where(ps ...predicate.PackageVersion) *PackageVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *PackageVersionUpdate) SetPackageID(v int64) *PackageVersionUpdate {
	_u.mutation.ResetPackageID()
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *PackageVersionUpdate) SetNillablePackageID(v *int64) *PackageVersionUpdate {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// AddPackageID adds value to the "package_id" field.
func (_u *PackageVersionUpdate) AddPackageID(v int64) *PackageVersionUpdate {
	_u.mutation.AddPackageID(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *PackageVersionUpdate) SetRevision(v string) *PackageVersionUpdate {
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *PackageVersionUpdate) SetNillableRevision(v *string) *PackageVersionUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// SetSourceDigest sets the "source_digest" field.
func (_u *PackageVersionUpdate) SetSourceDigest(v string) *PackageVersionUpdate {
	_u.mutation.SetSourceDigest(v)
	return _u
}

// SetNillableSourceDigest sets the "source_digest" field if the given value is not nil.
func (_u *PackageVersionUpdate) SetNillableSourceDigest(v *string) *PackageVersionUpdate {
	if v != nil {
		_u.SetSourceDigest(*v)
	}
	return _u
}

// SetPkgver sets the "pkgver" field.
func (_u *PackageVersionUpdate) SetPkgver(v string) *PackageVersionUpdate {
	_u.mutation.SetPkgver(v)
	return _u
}

// SetNillablePkgver sets the "pkgver" field if the given value is not nil.
func (_u *PackageVersionUpdate) SetNillablePkgver(v *string) *PackageVersionUpdate {
	if v != nil {
		_u.SetPkgver(*v)
	}
	return _u
}

// SetPkgrel sets the "pkgrel" field.
func (_u *PackageVersionUpdate) SetPkgrel(v string) *PackageVersionUpdate {
	_u.mutation.SetPkgrel(v)
	return _u
}

// SetNillablePkgrel sets the "pkgrel" field if the given value is not nil.
func (_u *PackageVersionUpdate) SetNillablePkgrel(v *string) *PackageVersionUpdate {
	if v != nil {
		_u.SetPkgrel(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PackageVersionUpdate) SetMetadata(v map[string]interface{}) *PackageVersionUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// Mutation returns the PackageVersionMutation object of the builder.
func (_u *PackageVersionUpdate) Mutation() *PackageVersionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PackageVersionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PackageVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PackageVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PackageVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PackageVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(packageversion.Table, packageversion.Columns, sqlgraph.NewFieldSpec(packageversion.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(packageversion.FieldPackageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPackageID(); ok {
		_spec.AddField(packageversion.FieldPackageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(packageversion.FieldRevision, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceDigest(); ok {
		_spec.SetField(packageversion.FieldSourceDigest, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pkgver(); ok {
		_spec.SetField(packageversion.FieldPkgver, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pkgrel(); ok {
		_spec.SetField(packageversion.FieldPkgrel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(packageversion.FieldMetadata, field.TypeJSON, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{packageversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PackageVersionUpdateOne is the builder for updating a single PackageVersion entity.
type PackageVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PackageVersionMutation
}

// SetPackageID sets the "package_id" field.
func (_u *PackageVersionUpdateOne) SetPackageID(v int64) *PackageVersionUpdateOne {
	_u.mutation.ResetPackageID()
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *PackageVersionUpdateOne) SetNillablePackageID(v *int64) *PackageVersionUpdateOne {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// AddPackageID adds value to the "package_id" field.
func (_u *PackageVersionUpdateOne) AddPackageID(v int64) *PackageVersionUpdateOne {
	_u.mutation.AddPackageID(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *PackageVersionUpdateOne) SetRevision(v string) *PackageVersionUpdateOne {
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *PackageVersionUpdateOne) SetNillableRevision(v *string) *PackageVersionUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// SetSourceDigest sets the "source_digest" field.
func (_u *PackageVersionUpdateOne) SetSourceDigest(v string) *PackageVersionUpdateOne {
	_u.mutation.SetSourceDigest(v)
	return _u
}

// SetNillableSourceDigest sets the "source_digest" field if the given value is not nil.
func (_u *PackageVersionUpdateOne) SetNillableSourceDigest(v *string) *PackageVersionUpdateOne {
	if v != nil {
		_u.SetSourceDigest(*v)
	}
	return _u
}

// SetPkgver sets the "pkgver" field.
func (_u *PackageVersionUpdateOne) SetPkgver(v string) *PackageVersionUpdateOne {
	_u.mutation.SetPkgver(v)
	return _u
}

// SetNillablePkgver sets the "pkgver" field if the given value is not nil.
func (_u *PackageVersionUpdateOne) SetNillablePkgver(v *string) *PackageVersionUpdateOne {
	if v != nil {
		_u.SetPkgver(*v)
	}
	return _u
}

// SetPkgrel sets the "pkgrel" field.
func (_u *PackageVersionUpdateOne) SetPkgrel(v string) *PackageVersionUpdateOne {
	_u.mutation.SetPkgrel(v)
	return _u
}

// SetNillablePkgrel sets the "pkgrel" field if the given value is not nil.
func (_u *PackageVersionUpdateOne) SetNillablePkgrel(v *string) *PackageVersionUpdateOne {
	if v != nil {
		_u.SetPkgrel(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PackageVersionUpdateOne) SetMetadata(v map[string]interface{}) *PackageVersionUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// Mutation returns the PackageVersionMutation object of the builder.
func (_u *PackageVersionUpdateOne) Mutation() *PackageVersionMutation {
	return _u.mutation
}

// Where appends a list predicates to the PackageVersionUpdate builder.
func (_u *PackageVersionUpdateOne) Where(ps ...predicate.PackageVersion) *PackageVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PackageVersionUpdateOne) Select(field string, fields ...string) *PackageVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PackageVersion entity.
func (_u *PackageVersionUpdateOne) Save(ctx context.Context) (*PackageVersion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PackageVersionUpdateOne) SaveX(ctx context.Context) *PackageVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PackageVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PackageVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PackageVersionUpdateOne) sqlSave(ctx context.Context) (_node *PackageVersion, err error) {
	_spec := sqlgraph.NewUpdateSpec(packageversion.Table, packageversion.Columns, sqlgraph.NewFieldSpec(packageversion.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PackageVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, packageversion.FieldID)
		for _, f := range fields {
			if !packageversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != packageversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(packageversion.FieldPackageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPackageID(); ok {
		_spec.AddField(packageversion.FieldPackageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(packageversion.FieldRevision, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceDigest(); ok {
		_spec.SetField(packageversion.FieldSourceDigest, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pkgver(); ok {
		_spec.SetField(packageversion.FieldPkgver, field.TypeString, value)
	}
	if value, ok := _u.mutation.Pkgrel(); ok {
		_spec.SetField(packageversion.FieldPkgrel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(packageversion.FieldMetadata, field.TypeJSON, value)
	}
	_node = &PackageVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{packageversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
