// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/dudebehinddude/aurforge/ent/job"
	"github.com/dudebehinddude/aurforge/ent/managedpackage"
	"github.com/dudebehinddude/aurforge/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	jobFields := schema.Job{}.Fields()
	_ = jobFields
	// jobDescKind is the schema descriptor for kind field.
	jobDescKind := jobFields[1].Descriptor()
	// job.DefaultKind holds the default value on creation for the kind field.
	job.DefaultKind = jobDescKind.Default.(string)
	// jobDescAttempts is the schema descriptor for attempts field.
	jobDescAttempts := jobFields[6].Descriptor()
	// job.DefaultAttempts holds the default value on creation for the attempts field.
	job.DefaultAttempts = jobDescAttempts.Default.(int)
	managedpackageFields := schema.ManagedPackage{}.Fields()
	_ = managedpackageFields
	// managedpackageDescEnabled is the schema descriptor for enabled field.
	managedpackageDescEnabled := managedpackageFields[4].Descriptor()
	// managedpackage.DefaultEnabled holds the default value on creation for the enabled field.
	managedpackage.DefaultEnabled = managedpackageDescEnabled.Default.(bool)
	// managedpackageDescCreatedAt is the schema descriptor for created_at field.
	managedpackageDescCreatedAt := managedpackageFields[5].Descriptor()
	// managedpackage.DefaultCreatedAt holds the default value on creation for the created_at field.
	managedpackage.DefaultCreatedAt = managedpackageDescCreatedAt.Default.(func() time.Time)
	// managedpackageDescUpdatedAt is the schema descriptor for updated_at field.
	managedpackageDescUpdatedAt := managedpackageFields[6].Descriptor()
	// managedpackage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	managedpackage.DefaultUpdatedAt = managedpackageDescUpdatedAt.Default.(func() time.Time)
	// managedpackage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	managedpackage.UpdateDefaultUpdatedAt = managedpackageDescUpdatedAt.UpdateDefault.(func() time.Time)
}
