// Code generated by ent, DO NOT EDIT.

package auditevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/dudebehinddude/aurforge/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLTE(FieldID, id))
}

// PackageVersionID applies equality check predicate on the "package_version_id" field. It's identical to PackageVersionIDEQ.
func PackageVersionID(v int64) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldPackageVersionID, v))
}

// Severity applies equality check predicate on the "severity" field. It's identical to SeverityEQ.
func Severity(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldSeverity, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldCode, v))
}

// Detail applies equality check predicate on the "detail" field. It's identical to DetailEQ.
func Detail(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldDetail, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// PackageVersionIDEQ applies the EQ predicate on the "package_version_id" field.
func PackageVersionIDEQ(v int64) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldPackageVersionID, v))
}

// PackageVersionIDNEQ applies the NEQ predicate on the "package_version_id" field.
func PackageVersionIDNEQ(v int64) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNEQ(FieldPackageVersionID, v))
}

// PackageVersionIDIn applies the In predicate on the "package_version_id" field.
func PackageVersionIDIn(vs ...int64) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldIn(FieldPackageVersionID, vs...))
}

// PackageVersionIDNotIn applies the NotIn predicate on the "package_version_id" field.
func PackageVersionIDNotIn(vs ...int64) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNotIn(FieldPackageVersionID, vs...))
}

// PackageVersionIDGT applies the GT predicate on the "package_version_id" field.
func PackageVersionIDGT(v int64) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGT(FieldPackageVersionID, v))
}

// PackageVersionIDGTE applies the GTE predicate on the "package_version_id" field.
func PackageVersionIDGTE(v int64) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGTE(FieldPackageVersionID, v))
}

// PackageVersionIDLT applies the LT predicate on the "package_version_id" field.
func PackageVersionIDLT(v int64) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLT(FieldPackageVersionID, v))
}

// PackageVersionIDLTE applies the LTE predicate on the "package_version_id" field.
func PackageVersionIDLTE(v int64) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLTE(FieldPackageVersionID, v))
}

// SeverityEQ applies the EQ predicate on the "severity" field.
func SeverityEQ(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldSeverity, v))
}

// SeverityNEQ applies the NEQ predicate on the "severity" field.
func SeverityNEQ(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNEQ(FieldSeverity, v))
}

// SeverityIn applies the In predicate on the "severity" field.
func SeverityIn(vs ...string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldIn(FieldSeverity, vs...))
}

// SeverityNotIn applies the NotIn predicate on the "severity" field.
func SeverityNotIn(vs ...string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNotIn(FieldSeverity, vs...))
}

// SeverityGT applies the GT predicate on the "severity" field.
func SeverityGT(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGT(FieldSeverity, v))
}

// SeverityGTE applies the GTE predicate on the "severity" field.
func SeverityGTE(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGTE(FieldSeverity, v))
}

// SeverityLT applies the LT predicate on the "severity" field.
func SeverityLT(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLT(FieldSeverity, v))
}

// SeverityLTE applies the LTE predicate on the "severity" field.
func SeverityLTE(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLTE(FieldSeverity, v))
}

// SeverityContains applies the Contains predicate on the "severity" field.
func SeverityContains(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldContains(FieldSeverity, v))
}

// SeverityHasPrefix applies the HasPrefix predicate on the "severity" field.
func SeverityHasPrefix(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldHasPrefix(FieldSeverity, v))
}

// SeverityHasSuffix applies the HasSuffix predicate on the "severity" field.
func SeverityHasSuffix(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldHasSuffix(FieldSeverity, v))
}

// SeverityEqualFold applies the EqualFold predicate on the "severity" field.
func SeverityEqualFold(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEqualFold(FieldSeverity, v))
}

// SeverityContainsFold applies the ContainsFold predicate on the "severity" field.
func SeverityContainsFold(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldContainsFold(FieldSeverity, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldContainsFold(FieldCode, v))
}

// DetailEQ applies the EQ predicate on the "detail" field.
func DetailEQ(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldDetail, v))
}

// DetailNEQ applies the NEQ predicate on the "detail" field.
func DetailNEQ(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNEQ(FieldDetail, v))
}

// DetailIn applies the In predicate on the "detail" field.
func DetailIn(vs ...string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldIn(FieldDetail, vs...))
}

// DetailNotIn applies the NotIn predicate on the "detail" field.
func DetailNotIn(vs ...string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNotIn(FieldDetail, vs...))
}

// DetailGT applies the GT predicate on the "detail" field.
func DetailGT(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGT(FieldDetail, v))
}

// DetailGTE applies the GTE predicate on the "detail" field.
func DetailGTE(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGTE(FieldDetail, v))
}

// DetailLT applies the LT predicate on the "detail" field.
func DetailLT(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLT(FieldDetail, v))
}

// DetailLTE applies the LTE predicate on the "detail" field.
func DetailLTE(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLTE(FieldDetail, v))
}

// DetailContains applies the Contains predicate on the "detail" field.
func DetailContains(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldContains(FieldDetail, v))
}

// DetailHasPrefix applies the HasPrefix predicate on the "detail" field.
func DetailHasPrefix(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldHasPrefix(FieldDetail, v))
}

// DetailHasSuffix applies the HasSuffix predicate on the "detail" field.
func DetailHasSuffix(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldHasSuffix(FieldDetail, v))
}

// DetailEqualFold applies the EqualFold predicate on the "detail" field.
func DetailEqualFold(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEqualFold(FieldDetail, v))
}

// DetailContainsFold applies the ContainsFold predicate on the "detail" field.
func DetailContainsFold(v string) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldContainsFold(FieldDetail, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuditEvent {
	return predicate.AuditEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuditEvent) predicate.AuditEvent {
	return predicate.AuditEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuditEvent) predicate.AuditEvent {
	return predicate.AuditEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuditEvent) predicate.AuditEvent {
	return predicate.AuditEvent(sql.NotPredicates(p))
}
