// Code generated by ent, DO NOT EDIT.

package dependency

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the dependency type in the database.
	Label = "dependency"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPackageVersionID holds the string denoting the package_version_id field in the database.
	FieldPackageVersionID = "package_version_id"
	// FieldDependencyName holds the string denoting the dependency_name field in the database.
	FieldDependencyName = "dependency_name"
	// FieldDependencyKind holds the string denoting the dependency_kind field in the database.
	FieldDependencyKind = "dependency_kind"
	// Table holds the table name of the dependency in the database.
	Table = "dependencies"
)

// Columns holds all SQL columns for dependency fields.
var Columns = []string{
	FieldID,
	FieldPackageVersionID,
	FieldDependencyName,
	FieldDependencyKind,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// DependencyKind defines the type for the "dependency_kind" enum field.
type DependencyKind string

// DependencyKind values.
const (
	DependencyKindRepo DependencyKind = "repo"
	DependencyKindAur  DependencyKind = "aur"
)

func (dk DependencyKind) String() string {
	return string(dk)
}

// DependencyKindValidator is a validator for the "dependency_kind" field enum values. It is called by the builders before save.
func DependencyKindValidator(dk DependencyKind) error {
	switch dk {
	case DependencyKindRepo, DependencyKindAur:
		return nil
	default:
		return fmt.Errorf("dependency: invalid enum value for dependency_kind field: %q", dk)
	}
}

// OrderOption defines the ordering options for the Dependency queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPackageVersionID orders the results by the package_version_id field.
func ByPackageVersionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPackageVersionID, opts...).ToFunc()
}

// ByDependencyName orders the results by the dependency_name field.
func ByDependencyName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDependencyName, opts...).ToFunc()
}

// ByDependencyKind orders the results by the dependency_kind field.
func ByDependencyKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDependencyKind, opts...).ToFunc()
}
