// Code generated by ent, DO NOT EDIT.

package dependency

import (
	"entgo.io/ent/dialect/sql"
	"github.com/dudebehinddude/aurforge/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Dependency {
	return predicate.Dependency(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Dependency {
	return predicate.Dependency(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Dependency {
	return predicate.Dependency(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Dependency {
	return predicate.Dependency(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Dependency {
	return predicate.Dependency(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Dependency {
	return predicate.Dependency(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Dependency {
	return predicate.Dependency(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Dependency {
	return predicate.Dependency(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Dependency {
	return predicate.Dependency(sql.FieldLTE(FieldID, id))
}

// PackageVersionID applies equality check predicate on the "package_version_id" field. It's identical to PackageVersionIDEQ.
func PackageVersionID(v int64) predicate.Dependency {
	return predicate.Dependency(sql.FieldEQ(FieldPackageVersionID, v))
}

// DependencyName applies equality check predicate on the "dependency_name" field. It's identical to DependencyNameEQ.
func DependencyName(v string) predicate.Dependency {
	return predicate.Dependency(sql.FieldEQ(FieldDependencyName, v))
}

// PackageVersionIDEQ applies the EQ predicate on the "package_version_id" field.
func PackageVersionIDEQ(v int64) predicate.Dependency {
	return predicate.Dependency(sql.FieldEQ(FieldPackageVersionID, v))
}

// PackageVersionIDNEQ applies the NEQ predicate on the "package_version_id" field.
func PackageVersionIDNEQ(v int64) predicate.Dependency {
	return predicate.Dependency(sql.FieldNEQ(FieldPackageVersionID, v))
}

// PackageVersionIDIn applies the In predicate on the "package_version_id" field.
func PackageVersionIDIn(vs ...int64) predicate.Dependency {
	return predicate.Dependency(sql.FieldIn(FieldPackageVersionID, vs...))
}

// PackageVersionIDNotIn applies the NotIn predicate on the "package_version_id" field.
func PackageVersionIDNotIn(vs ...int64) predicate.Dependency {
	return predicate.Dependency(sql.FieldNotIn(FieldPackageVersionID, vs...))
}

// PackageVersionIDGT applies the GT predicate on the "package_version_id" field.
func PackageVersionIDGT(v int64) predicate.Dependency {
	return predicate.Dependency(sql.FieldGT(FieldPackageVersionID, v))
}

// PackageVersionIDGTE applies the GTE predicate on the "package_version_id" field.
func PackageVersionIDGTE(v int64) predicate.Dependency {
	return predicate.Dependency(sql.FieldGTE(FieldPackageVersionID, v))
}

// PackageVersionIDLT applies the LT predicate on the "package_version_id" field.
func PackageVersionIDLT(v int64) predicate.Dependency {
	return predicate.Dependency(sql.FieldLT(FieldPackageVersionID, v))
}

// PackageVersionIDLTE applies the LTE predicate on the "package_version_id" field.
func PackageVersionIDLTE(v int64) predicate.Dependency {
	return predicate.Dependency(sql.FieldLTE(FieldPackageVersionID, v))
}

// DependencyNameEQ applies the EQ predicate on the "dependency_name" field.
func DependencyNameEQ(v string) predicate.Dependency {
	return predicate.Dependency(sql.FieldEQ(FieldDependencyName, v))
}

// DependencyNameNEQ applies the NEQ predicate on the "dependency_name" field.
func DependencyNameNEQ(v string) predicate.Dependency {
	return predicate.Dependency(sql.FieldNEQ(FieldDependencyName, v))
}

// DependencyNameIn applies the In predicate on the "dependency_name" field.
func DependencyNameIn(vs ...string) predicate.Dependency {
	return predicate.Dependency(sql.FieldIn(FieldDependencyName, vs...))
}

// DependencyNameNotIn applies the NotIn predicate on the "dependency_name" field.
func DependencyNameNotIn(vs ...string) predicate.Dependency {
	return predicate.Dependency(sql.FieldNotIn(FieldDependencyName, vs...))
}

// DependencyNameGT applies the GT predicate on the "dependency_name" field.
func DependencyNameGT(v string) predicate.Dependency {
	return predicate.Dependency(sql.FieldGT(FieldDependencyName, v))
}

// DependencyNameGTE applies the GTE predicate on the "dependency_name" field.
func DependencyNameGTE(v string) predicate.Dependency {
	return predicate.Dependency(sql.FieldGTE(FieldDependencyName, v))
}

// DependencyNameLT applies the LT predicate on the "dependency_name" field.
func DependencyNameLT(v string) predicate.Dependency {
	return predicate.Dependency(sql.FieldLT(FieldDependencyName, v))
}

// DependencyNameLTE applies the LTE predicate on the "dependency_name" field.
func DependencyNameLTE(v string) predicate.Dependency {
	return predicate.Dependency(sql.FieldLTE(FieldDependencyName, v))
}

// DependencyNameContains applies the Contains predicate on the "dependency_name" field.
func DependencyNameContains(v string) predicate.Dependency {
	return predicate.Dependency(sql.FieldContains(FieldDependencyName, v))
}

// DependencyNameHasPrefix applies the HasPrefix predicate on the "dependency_name" field.
func DependencyNameHasPrefix(v string) predicate.Dependency {
	return predicate.Dependency(sql.FieldHasPrefix(FieldDependencyName, v))
}

// DependencyNameHasSuffix applies the HasSuffix predicate on the "dependency_name" field.
func DependencyNameHasSuffix(v string) predicate.Dependency {
	return predicate.Dependency(sql.FieldHasSuffix(FieldDependencyName, v))
}

// DependencyNameEqualFold applies the EqualFold predicate on the "dependency_name" field.
func DependencyNameEqualFold(v string) predicate.Dependency {
	return predicate.Dependency(sql.FieldEqualFold(FieldDependencyName, v))
}

// DependencyNameContainsFold applies the ContainsFold predicate on the "dependency_name" field.
func DependencyNameContainsFold(v string) predicate.Dependency {
	return predicate.Dependency(sql.FieldContainsFold(FieldDependencyName, v))
}

// DependencyKindEQ applies the EQ predicate on the "dependency_kind" field.
func DependencyKindEQ(v DependencyKind) predicate.Dependency {
	return predicate.Dependency(sql.FieldEQ(FieldDependencyKind, v))
}

// DependencyKindNEQ applies the NEQ predicate on the "dependency_kind" field.
func DependencyKindNEQ(v DependencyKind) predicate.Dependency {
	return predicate.Dependency(sql.FieldNEQ(FieldDependencyKind, v))
}

// DependencyKindIn applies the In predicate on the "dependency_kind" field.
func DependencyKindIn(vs ...DependencyKind) predicate.Dependency {
	return predicate.Dependency(sql.FieldIn(FieldDependencyKind, vs...))
}

// DependencyKindNotIn applies the NotIn predicate on the "dependency_kind" field.
func DependencyKindNotIn(vs ...DependencyKind) predicate.Dependency {
	return predicate.Dependency(sql.FieldNotIn(FieldDependencyKind, vs...))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Dependency) predicate.Dependency {
	return predicate.Dependency(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Dependency) predicate.Dependency {
	return predicate.Dependency(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Dependency) predicate.Dependency {
	return predicate.Dependency(sql.NotPredicates(p))
}
