// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Artifact is the predicate function for artifact builders.
type Artifact func(*sql.Selector)

// AuditEvent is the predicate function for auditevent builders.
type AuditEvent func(*sql.Selector)

// Dependency is the predicate function for dependency builders.
type Dependency func(*sql.Selector)

// Job is the predicate function for job builders.
type Job func(*sql.Selector)

// ManagedPackage is the predicate function for managedpackage builders.
type ManagedPackage func(*sql.Selector)

// PackageVersion is the predicate function for packageversion builders.
type PackageVersion func(*sql.Selector)
